### ISSUE TITLE
It would be nice to have tooltips on the chevrons in the navigation bar

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#102]
Add the following tooltips to the chevrons on the navigation bar on hover:
`<` - `previous verse`
`<< `- `previous chapter`
`>` - `next verse`
`>>` - `next chapter`

**Comment by cckozie** [comment]
Looks good in v0.9.0 build 008141c

**Comment by elsylambert** [comment]
Tooltips on Chevrons look good in v0.9.0 build 008141.

**Comment by cckozie** [comment]
Tested in Test Scripture Navigation
