### ISSUE TITLE
Lexicons shows for UST text on the Scripture card even when the scripture is changed from UGNT to UST.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#104]
e.g. for Mat 1:22,
1. On the UGNT card, click on the three dot menu and select a different scripture e.g UST.
2. Hover the mouse over the highlighted text in the UGNT CARD in step 1. Note that the lexicon pop up shows up.
![Screen Shot 2021-03-16 at 9.35.28 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/b3a39c01-2c03-49c0-8cb1-5e3d98a0a6fa)

**Comment by cckozie** [comment]
This has been fixed in v0.9.0 build 87451c8, but there are other lexicon problems which I wrote up in #149.

**Comment by elsylambert** [comment]
Issue is fixed in v0.9.0 build 4ec92f2.
