### ISSUE TITLE
Close button(X) required in the feedback form

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#105]
There is no option currently to close the feedback form.
![Screen Shot 2021-03-16 at 1.18.43 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/cfb93a6b-9940-4e00-ab3c-f5fc07373b79)

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie Fixed in v0.9.0 build c721e37

**Comment by cckozie** [comment]
I'm seeing it in v0.9.0 build 87451c8

**Comment by elsylambert** [comment]
Looks good in v0.9.0 build 4ec92f2.
