### ISSUE TITLE
Email field in the feedback form is not validated.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#106]
Email input box displays text on hover "to include @" in the email address, but does not validate the text. The form is submitted successfully with a faulty email address(without an @ symbol).

Ensure that the input follows an email pattern.

DoD:
---
User is warned about invalid email and prevented from submitting the form.

Details:
---
HTML input tag allows 'pattern' to be specified as email.
https://html5-tutorial.net/form-validation/validating-email/
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email

**Comment by PhotoNomad0** [comment]
@birchamp & @elsylambert 

Here are examples using the built in validation hinting text of the browser.  Does this look sufficient?

**For Chrome:**

![Screen Shot 2021-08-12 at 9 08 26 AM](https://user-images.githubusercontent.com/14238574/129203384-d58eaf6f-1de2-45b2-b543-45aa9f148003.png)
![Screen Shot 2021-08-12 at 9 08 41 AM](https://user-images.githubusercontent.com/14238574/129203429-3143cdbf-4d51-4ee9-a7f1-e24b8ef62f9d.png)
![Screen Shot 2021-08-12 at 9 09 05 AM](https://user-images.githubusercontent.com/14238574/129203442-dd11d374-a0c2-41a6-8cb2-babf90d87ad0.png)
![Screen Shot 2021-08-12 at 9 09 13 AM](https://user-images.githubusercontent.com/14238574/129203468-56180d0b-7133-40b8-a8e7-e19848ab404b.png)
![Screen Shot 2021-08-12 at 9 09 27 AM](https://user-images.githubusercontent.com/14238574/129203489-451585ce-e917-43ad-808e-878a9e35de3a.png)
![Screen Shot 2021-08-12 at 9 09 46 AM](https://user-images.githubusercontent.com/14238574/129203518-0bbb8e8e-0568-434e-8822-acf30f5de71f.png)

For Firefox and Safari there is only a generic prompt:

FireFox:
![Screen Shot 2021-08-12 at 9 15 27 AM](https://user-images.githubusercontent.com/14238574/129203629-4d4d241c-586f-4fb6-8641-4c11a0abc936.png)

Safari: 
![Screen Shot 2021-08-12 at 9 15 42 AM](https://user-images.githubusercontent.com/14238574/129203684-ed0f8bf3-dc4f-4405-b3b9-5881e29ed1de.png)

**Comment by PhotoNomad0** [comment]
We can make things more complex using more complicated regex, but that can get complicated and potentially disallow valid email addresses.

Or we can replace the error message with our own message

**Comment by birchamp** [comment]
LGTM

**Comment by PhotoNomad0** [comment]
Revised implementation based on Zulip thread:
* ...it waits until you submit and then shows the error under the field until you start typing again.
* ...the caret jumps to the email field after failing to submit.

Another change is that email warning does not clear until the email address is changed to a valid address (according to browser default validation)

**Comment by PhotoNomad0** [comment]
@elsylambert - revised for forms based testing in GWE v1.0.0 build 1c04778

**Comment by elsylambert** [comment]
v1.0.0 build 1c04778.
There are two problems:
1. The validation happens for "@" but not for ".domain" i.e it accepts abc@def as email. It should validate for the email pattern "abc@def.xyz".
2. After submitting the form, Submit button stays active and clickable, until you click "ok" on the message below.

![Screen Shot 2021-08-16 at 4.55.51 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/7a19d06d-8a88-4425-94a8-1bab7714ea8c)

**Comment by PhotoNomad0** [comment]
@elsylambert  For item 1 above, @birchamp decided we would stay with the default email validation in the browser.

**Comment by birchamp** [comment]
1. yes, default validation is sufficient for now.
2. @PhotoNomad0 are you saying that the normal behavior isn't to clear the form?

**Comment by PhotoNomad0** [comment]
@birchamp yes, we do not do any clearing of the form.  But I think @elsylambert is suggesting the submit button should be disabled if the email address was failed validation.  We could add some logic for that, but right now we are not invalidating the submit button based on email address validation.

**Comment by birchamp** [comment]
@PhotoNomad0 @elsylambert now that we've split this out is this still a QA fail?

**Comment by PhotoNomad0** [comment]
@birchamp I say it's not.

**Comment by elsylambert** [comment]
Passing this issue as per the DOD. Separated point 2 and wrote up in #281.
