### ISSUE TITLE
Markdown view not available for translationWords Article

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#107]
Add markdown toggle and view to TranslationWords articles. 

DoD: TranslationWords articles can be viewed in markdown the way other resources can. 

======================
translation Notes and translationAcademy have a button to toggle the Markdown view but translationWords do not. Is it designed that way not to show MD?

**Comment by elsylambert** [comment]
v0.9.0 build 96e267c
Markdown view switch is available for tW cards and is working as expected. The switch is persisted by user login.

**Comment by elsylambert** [comment]
v0.9.0 build 96e267c
Markdown switch is available in tW article card. Toggle works fine and is persisted by user logins,

**Comment by cckozie** [comment]
Markdown is available  and works on the tW card in v0.9.0 build 2f4b7ee

**Comment by cckozie** [comment]
Tested in Test Persistence by User
