### ISSUE TITLE
QA needs to be able to see a unique build number

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#115]
Add version number and build number to the lower left of the screen on the blue bar.
![image](https://user-images.githubusercontent.com/10272744/112043263-dbedb300-8b1e-11eb-9c5e-973662648260.png)

**Comment by birchamp** [comment]
@birchamp add screenshot from 1.0

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert Latest build is here (https://create-app.netlify.app/) with latest commit hash 66d96f2

**Comment by PhotoNomad0** [comment]
On the Footer added two text spans. One with larger text id='build_version', and the smaller text id='build_hash'

**Comment by cckozie** [comment]
Looking good in v0.2.0 build 66d96f2, even with id attributes!
