### ISSUE TITLE
TQ card needs to handle new TSV spec

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#116]
TQ cards should handle the newest TSV spec:

The final spec for TSVs is here: 
https://forum.door43.org/t/parascriptural-tab-separated-value-format-specification-v2/870

An example of the TSV for TQ is here: https://git.door43.org/unfoldingWord/en_tq/src/branch/newFormat

**Comment by birchamp** [comment]
Aren't these are already handled?

**Comment by birchamp** [comment]
This is handled by create-app#124

**Comment by PhotoNomad0** [comment]
@cckozie This should be fixed in build v0.2.0 build dbfbebc
@elsylambert

**Comment by elsylambert** [comment]
v0.9.0 build ab13659
The new TQ tsv format looks good in the TQ card and works fine.

**Comment by elsylambert** [comment]
v0.9.0 build 736dc08
TQ card looks good.

**Comment by cckozie** [comment]
How can we test this? I'm seeing markdown in the tQ files in both test_org and test_org2.

**Comment by birchamp** [comment]
@mannycolon is going to make a test_org3 that includes TQ in TSV format.

**Comment by cckozie** [comment]
This is blocked until we have a proper repo to test from. (test_org3 has problems)

**Comment by cckozie** [comment]
v0.9.0 build 008141c
tQ card is properly handling the new format as in test_org3

**Comment by elsylambert** [comment]
v0.9.0 build 008141c
TQ card is looking fine in the new format in test_org3.
![Screen Shot 2021-05-05 at 12.32.53 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/e39d2eb4-6d54-4eda-baa0-3f58827ebd25)
