### ISSUE TITLE
We need a way for the user to recover from app crashes

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#117]
Since stored values in local storage are used when a user logs in, they will immediately be taken to wherever they were when they last used the app. Hence, if the last thing that happened when fully logged in was an app crash, they will go to that same place and experience the same crash every time they log in. They will have to use a different browser in order to continue their work.
There needs to a way for the user to resolve this situation, or for the app to detect and fix it (semi) automatically.

**Comment by mannycolon** [comment]
https://kentcdodds.com/blog/use-react-error-boundary-to-handle-errors-in-react

**Comment by cckozie** [comment]
I am no longer able to create the type of error that put the app into the loop, so there is really no way to test this fix.
