### ISSUE TITLE
Scroll the text to the top on the tW card when the user clicks one of its chevrons to change the tW being displayed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#119]
Currently the text remains scrolled to wherever it was when the user clicked the chevron.

DoD: The card scrolls to the top of the text when the user changes articles.

https://images.zenhubusercontent.com/310359593/c5277b89-d18b-442e-a99a-bce9453a0e62/create_2_0_issue_119.mp4

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie Working in v0.9.0 build 9846e94

**Comment by cckozie** [comment]
Working as expected in v0.9.0 build 87451c8

**Comment by elsylambert** [comment]
Works as expected in v0.9.0 build 4ec92f2.
