### ISSUE TITLE
 Link navigation

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#12]
Investigate:
* Add event listener on clicked link
* Klappy's method? (https://unfoldingword-box3.github.io/translation-helps/?owner=unfoldingword )
* is this a good candidate for a custom hook?
* New tab in browser as a fallback

Any links (scripture, TA, others?) in a card should direct to a read-only modal resource card that displays the linked article. The user should be able to close the modal card. Links within the modal should open in the same card. 

![Modal Card Framework 2021-03-11 10-13-38.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/7509cf77-8d25-40a4-8de8-ed34b0935dac)

**Comment by elsylambert** [comment]
v0.9.0 build 4ec92f2.
Link navigation to Article modal looks good. Modals can be dragged out of view which is written in #157.
