### ISSUE TITLE
Missing element id's on the tN card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#126]
The fields outlined in this screenshot should have unique id's

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/cf46dc75-1391-4973-8a97-993ab61e77ac)

**Comment by PhotoNomad0** [comment]
I believe they already have unique labels. I will double check tomorrow. If that is not sufficient we can add ids.

**Comment by PhotoNomad0** [comment]
@cckozie ^^^

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert Can test in latest: v0.2.0 build cbad9c9

**Comment by cckozie** [comment]
ID's look good in v0.9.0 build da4bfd6
