### ISSUE TITLE
Handle HTTP errors.

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#130]
Issue:
---
Users need to be informed of network errors that will cause problems with the app. The app needs to handle network issues gracefully. 
4 categories of issues should be distinguished for the user:

* No network connection - "Please check your network connection. No network connection detected."
* No connection to the server - "Please check your internet connection. The application is unable to reach the server."
* Server error - "The server returned an #nnn error. Please try again or submit feedback." (needs feedback button)
* Authentication error - "The application is no longer logged in. Please login again." (needs a button to get to a login prompt)

DoD:
---
HTTP errors result in one of the 4 responses above.

Details:
---
From tC: translationCore has encountered an unknown communications error. If this problem continues, please send "User Feedback" which is on option on the "Actions" button.

**Comment by birchamp** [comment]
@PhotoNomad0 please add the error table here.

**Comment by PhotoNomad0** [comment]
**HTTP Error Codes (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status for reference):**

| Syntax | Description | Error Message |
| ------- | ----------- | --------------- |
| 200 | Success | _show no error message_ |
| 2xx | various partial success codes [1] |  |
| 1xx | informational responses [2] |  |
| 3xx | redirection requests [3] |  |
| 5xx | server errors [4] |  |
| 401 | server errors [4] |  |

**Notes:**
1 Codes other than 200 would typically be unexpected server responses
2 unexpected server responses
3 unsupported redirects to different URL
4 server errors that are not expected

Bruce McLean: 200 is success
the other 2xx codes, 1xx codes, 3xx codes, and 5xx codes are unexpected server errors

Bruce McLean: 4xx codes are various client errors that may have unique messages.

**Comment by PhotoNomad0** [comment]
**Notes:**

Modules to update:

| Location | API used | TODO |
| ------- | ----------- | --------------- |
| (get orgs) app/TranslationSettings | fetch - HTTP codes | can modify inline |
| (validate user token) app/AuthContextProvider.getAuth | fetch - HTTP codes | can modify inline |
| (drawer - goes to feedback page) app/api/feedback | sgMail - HTTP codes | can modify inline |
| app/pages/feedback.onSubmitFeedback | fetch - HTTP codes | can modify inline |
...

**Comment by PhotoNomad0** [comment]
**Note:**

gitea-react-toolkit responds to communication errors by doing a check to see if server is online:
- first checks that network is disconnected - if so it throws exception of ERROR_NETWORK_DISCONNECTED
- next calls DCS api to see if server is responding - if not returns exception of ERROR_SERVER_UNREACHABLE

**Comment by PhotoNomad0** [comment]
**GatewayEdit - Network access to convert tasks:**

- [ ] (get orgs) app/TranslationSettings - _inprocess_
- [ ] (validate user token) app/AuthContextProvider.getAuth
- [ ] (get bibles) app/Workspace | ? | calls getResourceBibles()
- [ ] (send feedback) app/api/feedback | sgMail - HTTP codes | can fix inline
- [ ] (login) AuthenticationContext | ? | fix in gitea-react-toolkit, useAuthentication()

**Comment by PhotoNomad0** [comment]
@birchamp , @cckozie , @elsylambert -  Need some feedback on UI design for the Network error Prompt.  This is a quick mock up using defaults.  How should it look?

<img width="939" alt="Screen Shot 2021-05-04 at 7 10 08 AM" src="https://user-images.githubusercontent.com/14238574/116995523-2a5aa980-aca8-11eb-882c-b7f67dc238a3.png">

**Comment by birchamp** [comment]
@PhotoNomad0 I really like it.  Can you add a button labeled 'close' to the lower right corner and move the feedback button over to the left of the close button?

**Comment by cckozie** [comment]
@PhotoNomad0 
This from Elsy in Zulip:
My two cents: The “Send feedback” button should be on the right side, keeping it consistent with other modals. I think the error message font should be a bit bigger cause the text looks smaller compared to the feedback button size.

From me: 
I agree with Elsy, I'd bump the font size on both of the non-button texts. I would also suggest making the second phrase an actual sentence: "No network connection was detected."

**Comment by PhotoNomad0** [comment]
@birchamp , @cckozie , @elsylambert - Does this look better?

<img width="868" alt="Screen Shot 2021-05-04 at 3 52 45 PM" src="https://user-images.githubusercontent.com/14238574/117062015-e213a980-acf0-11eb-8ce1-ab6d73bd343f.png">

**Comment by cckozie** [comment]
@PhotoNomad0 @birchamp @elsylambert 
I like the font size much better, but think we should follow the standard we had in tC that the cancel button is always on the left even if it is the default button.

**Comment by birchamp** [comment]
Looks good.  Go ahead and switch the buttons but leave the colors the same.

**Comment by PhotoNomad0** [comment]
@birchamp , @cckozie , @elsylambert - OK, swapped buttons and added a bit of vertical spacing per @mannycolon 's suggestion.

<img width="889" alt="Screen Shot 2021-05-04 at 6 54 12 PM" src="https://user-images.githubusercontent.com/14238574/117079665-38d9ad00-ad0a-11eb-85d2-a95f8202906f.png">

**Comment by cckozie** [comment]
I like it:)

**Comment by birchamp** [comment]
@PhotoNomad0 Looks really good. I assume the cancel button will be right-aligned when the 'send feedback' is hidden.

**Comment by PhotoNomad0** [comment]
@birchamp , @cckozie , @elsylambert - the only time this would show up for the user is when the internet is up but DCS is not responding.

**Comment by birchamp** [comment]
@PhotoNomad0 yes a retry makes sense, but in this case do we want the Retry to be the default? In other words should you make the retry blue?

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @elsylambert @mannycolon In after party we decided that for the resource cards, on network error we will display a single popup (even though there are multiple cards having problems).

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @elsylambert @mannycolon Just be aware that clicking retry before networking is fixed will cause the browser to show an error such as: 

![Screen Shot 2021-05-17 at 4 45 39 PM](https://user-images.githubusercontent.com/14238574/118554505-848b4e00-b72f-11eb-9392-9775b3da7f8f.png)

Perhaps we should add instructions to the end of the message when the retry button is displayed.  Something like "Correct the network issue and then Retry."?

**Comment by PhotoNomad0** [comment]
Notes:
- have it working on failures fetching project manifests, now working on fetching individual articles.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert This is in v0.9.0 build abbbdd5

**Comment by cckozie** [comment]
v0.9.0 build abbbdd5
Case 1: (no network conneciton) functions as stated in the issue description
Case 2: (no connection to server)
Test setup: 
- Start in running application on main page
- Disconnect from Internet
- Navigate to Account Settings page
Chrome on Mac:
Initial screen shows this:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/080f5922-411c-41f8-a65a-12ad94d4a924)

After 30 seconds this message is displayed
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/0843f3e8-ed1e-4e39-8ab3-0d9cbf48081d)

After 60 seconds (total) this message is displayed:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/f29ba109-dad5-4970-9a8f-9604c5fc2724)

If the internet connection is reestablished and the user clicks the Retry button, the Login screen is presented.

**Comment by elsylambert** [comment]
When the connection is lost while user is on the Project page and user tries to navigate the verses from the top navigation, the Network connection error message is shown, which is fine, but when the Cancel button is clicked, it is stuck cause the app tries to load the previous page but fails and the error message is shown again. Please see the video for more clarity:
https://images.zenhubusercontent.com/310359593/8b629b69-8529-4565-b146-983b17ed49d5/no_connection_error.mp4

**Comment by PhotoNomad0** [comment]
> v0.9.0 build [abbbdd5](https://github.com/unfoldingWord/gateway-edit/commit/abbbdd51e07169a6ec479409dc5478c0809f3d7c)
> Case 1: (no network conneciton) functions as stated in the issue description
> Case 2: (no connection to server)
> Test setup:
> 
>     * Start in running application on main page
> 
>     * Disconnect from Internet
> 
>     * Navigate to Account Settings page
>       Chrome on Mac:
>       Initial screen shows this:
>       ![image.png](https://camo.githubusercontent.com/ec52b51f3a1d9fe5f60907a92a8d50cde3288f2a0804cee87e791f8733285880/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3536653161393331366361663536633964333864386466352f30383066353932322d343131632d343166382d613635612d313261643934643461393234)
> 
> 
> After 30 (or sometimes 60) seconds this message is displayed
> ![image.png](https://camo.githubusercontent.com/e3f67b1c7dbccff2675ec8ca516b903a092aad4092d107be7552d4eb64b7800d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3536653161393331366361663536633964333864386466352f30383433663365382d656431652d346533392d386162332d306439636266343830383164)
> 
> After another 30 seconds this message is displayed:
> ![image.png](https://camo.githubusercontent.com/b0b6ea7aac09721bb284f991d6d0a4d53bb01e64e49d9a2d89835c18a2f9d33f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3536653161393331366361663536633964333864386466352f66323962613130392d646164352d343937302d396138662d393630346335666332373234)
> 
> If the internet connection is reestablished and the user clicks the Retry button, the Login screen is presented.
> If the user clicks the Retry button before the Internet connection has be reestablished, the browser issues a message.
> 
> On Macbook and Firefox, the results are similar, but the last message is different
> 

@cckozie I am not seeing what you are seeing.  When you say disconnect from internet, are you disconnecting your ethernet or wifi?  Or are you disconnecting your cable modem?

FYI - what I saw reproducing your steps (disconnecting the WIFI):
- the first time Chrome showed a white screen with message that page could not be loaded.  Unfortunately settings is a new page that hadn't yet been cached in Chrome, so no luck loading page.  Don't know if there is a simple solution for that
- the second time I did the steps, Chrome immediately showed:


![Screen Shot 2021-05-24 at 4 25 57 PM](https://user-images.githubusercontent.com/14238574/119403831-f2de8c00-bcac-11eb-890b-f48c6a0d6c87.png)

**Comment by PhotoNomad0** [comment]
@cckozie On Firefox I see a very long delay before seeing the above popup.  Likely because the page is already cached.

**Comment by PhotoNomad0** [comment]
@cckozie I am seeing an incorrect error when I disable the WAN connection in the router.  It is showing your first error message, and then after a long delay replacing with the correct error message.  Looks like the text in red is showing the older message until the network checking times out.  Taking a look into how to improved that.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert @birchamp - I'm thinking of adding a timeout when checking that DCS is responding. Does 5 seconds sound good enough?

**Comment by PhotoNomad0** [comment]
In standup it was decided to set timeout to 5 seconds the first time, and maybe 10 seconds on retry.

**Comment by cckozie** [comment]
@PhotoNomad0 - Just to clarify, when I say disconnect from Internet, that is disconnecting the router from the cable modem.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert  Fixes for long networking timeouts are here: https://develop--gateway-edit.netlify.app/, v1.0.0 build b334dd8

**Comment by elsylambert** [comment]
Wrote up my observation in #229- when user tries to close the network error modal in the Project page, the app seems to be stuck.

**Comment by cckozie** [comment]
v0.9.0 build b6be351
1. Navigate to Accounts Settings from main page with WiFi off:
- Quickly displays Network Error modal
- Clicking Retry causes browser's No internet page
- When WiFi is turned on, Login page is displayed
- Logging in takes user to Account Settings page with last values displayed (I expected the main page)

2. Navigate to Accounts Settings from main page with WiFi off:
- Quickly displays Network Error modal
- Clicking Cancel only removes the error modal and clears the Organization dropdown
- When WiFi is turned on, nothing happens. The Organization dropdown list will not open (it should)
- Clicking Save and Continue takes the user to the main page even though the Organization control was empty on the Account Settings page.

3. Turn WiFi off when on login page:
- When the Login button is clicked, a different Network Error modal is displayed. This one with only a Close button. (I think this should be the same error modal as in 1. and 2. above with Retry and Cancel options)
- When the Close button is clicked, the error modal is dismissed and the message "Something went wrong, please try again." is displayed on the login page. (At this point we know what went wrong and should display that rather than "something".
- Same thing repeats if the Login button is clicked again with still no WiFi
- After the WiFi is turned on and the Login button clicked, the user is taken to the Account Settings page with last values displayed (I expected the main page)

4. Change reference with WiFi off:
- It momentarily looks like the cards are being updated, but the the two button Network Error modal is displayed
- Clicking Retry causes browser's No internet page
- When WiFi is turned on, Login page is displayed
- Logging in takes user to the main page with the newly selected reference (I think that's correct, but was expecting the Accounts Setting page as in 1. above.

4. Change reference with WiFi off:
- It momentarily looks like the cards are being updated, but the the two button Network Error modal is displayed
- Clicking Cancel dismisses the error modal and momentarily displays the main page, but then quickly redisplays the error modal. (
- When WiFi is turned on, Login page is displayed
- Logging in takes user to the main page (I think that's correct, but was expecting the Accounts Setting page as in 1. above.

**Comment by elsylambert** [comment]
1.0.0 build 1c04778.
As per the DOD, getting the HTTP error messages for 4 cases, when the network is lost, connection to the server is lost, server error and authentication error when the user is no longer logged in.
