### ISSUE TITLE
Rebrand to gatewayEdit

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#131]
change branding and internal working name to 'gatewayEdit'

- [x] change repo name (manny)
- [x] zenhub board and release names (birch) 
- [x] app title (mclean)
- [x] change Netlify address (manny)
- [x] change Zulip stream (birch)
- [x] calendar events (birch)

**Comment by PhotoNomad0** [comment]
@birchamp In the app do we want to show `translationCore:gatewayEdit` or just `gatewayEdit`?

**Comment by birchamp** [comment]
Just 'gatewayEdit'
