### ISSUE TITLE
We should validate that user supplied scripture resource links are not for other known resource types

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#135]
Issue:
---
When the user attempts to add a non-scripture resource to a scripture card, the app should inform the user that only links to scripture resources are permitted in the field:
"This link does not point to a scripture resource."

DoD:
---
Attempting to add a non-scripture resource to a scripture card does not load the resource and displays the above message.

Details
---
v0.2.0 build cbad9c9

The app currently accepts links to non-scripture resource types and display an error message within the resource card rather than the settings card. e.g.

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/3aaa1bb8-9b63-4813-8ede-b051f1a00d41)

**Comment by PhotoNomad0** [comment]
Notes:
testing with `"https://git.door43.org/Door43-Catalog/en_twl"`

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie - fixes are in v0.9.0 build e7a0017

**Comment by cckozie** [comment]
Looks good in v0.9.0 build 3e62f25

**Comment by elsylambert** [comment]
Looks good in v0.9.0 build 3e62f25
