### ISSUE TITLE
The left margin of the text is never visible when horizontal scrolling is available on a card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#137]
v0.2.0 build cbad9c9

https://images.zenhubusercontent.com/310359593/ec1f42ec-1345-4736-aeb3-76a819bc1b03/issue_137.mp4

**Comment by cckozie** [comment]
v0.9.0 build edda059
It looks like horizontal scrolling has now been disabled, and vertical scrolling is expected to handle all text overflow. Now the vertical scrolling exhibits a similar problem in that the user is sometimes not able to scroll to the top of the text.

https://images.zenhubusercontent.com/310359593/381cb8e0-a7a4-441f-ab14-1c358210f8a2/issue_137_a.mp4

**Comment by cckozie** [comment]
This has been fixed in v0.9.0 build f601ed4

**Comment by elsylambert** [comment]
Not seeing Horizontal or vertical scrolling issue on the card in v0.9.0 build f601ed4.
