### ISSUE TITLE
The Tags field on the tN card moves both horizontally and vertically depending on the text in the Quote field

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#143]
v0.9.0 build da4bfd6
It is difficult to visually keep track of where the Tags field is on the card. The other fields appear to be stationary, except for the Annotations field which does move vertically which is probably appropriate.

https://images.zenhubusercontent.com/310359593/5c145d3c-1f51-4ebb-a8eb-99dd2855cb9b/issue_143.mp4

**Comment by elsylambert** [comment]
Looks good in v0.9.0 build 3e62f25.
