### ISSUE TITLE
Selected word is sometimes scrolled out of view when clicked on the tWL card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#147]
Issue:
---
When the user scrolls up to find the desired word on the twl card and then clicks on it, the app scrolls to the card to the top which then sometimes scrolls the selected word out of view.

DoD:
---
The TWL card doesn't scroll when clicking the selected word.

Details:
---
Note: TWs still need to scroll to the top when the article changes but not the TWL.

v0.9.0 build f1b02c0
When the user scrolls up to find the desired word on the twl card and then clicks on it, the app scrolls to the card to the top which then sometimes scrolls the selected word out of view.

https://images.zenhubusercontent.com/310359593/230c8080-fc61-42c5-a204-11b0fb5ca6c8/issue_147.mp4

**Comment by birchamp** [comment]
@PhotoNomad0 please add a link to where the code is for scrolling to top.

**Comment by PhotoNomad0** [comment]
@mannycolon - Here is the change I made: https://github.com/unfoldingWord/translation-helps-rcl/blob/main/src/components/Scrollable/Scrollable.js#L12

It would seem that the itemIndex is changing even though there is no index on the card?

**Comment by PhotoNomad0** [comment]
@mannycolon - Added some logging and found that when you click on a word in twl, that both twa and twl indexes are updating:

![Screen Shot 2021-04-19 at 8 37 12 AM](https://user-images.githubusercontent.com/14238574/115237515-a66ec200-a0ea-11eb-88c7-3874c27267cd.png)

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - Fixed in v0.9.0 build c1bb71c

**Comment by cckozie** [comment]
Works correctly in v0.9.0 build f601ed4

**Comment by elsylambert** [comment]
Not seeing this issue in v0.9.0 build 3e62f25. Words are not scrolled out of view on click in the tWL card.
