### ISSUE TITLE
The on-hover lexicon should be displayed on any scripture card that contains the original language

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#149]
Issue:
---
The on-hover lexicon info should be shown on any card that is currently displaying an OrigL text, even if the card didn't contain original language text to begin with.

DoD:
---
Any scripture card that has original language text displays the lexicon data on-hover.

Details:
---
In v0.9.0 build 87451c8, the on-hover lexicon is only displayed if scripture card 1 displays the original language. If the original language is displayed on scripture card 0 or 2, no lexicon is displayed on hover over.

**Comment by birchamp** [comment]
@PhotoNomad0 Can you reproduce this?

**Comment by PhotoNomad0** [comment]
@birchamp yes

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert Fixes in v0.9.0 build 17b95d3

**Comment by elsylambert** [comment]
Looks good in v0.9.0 build c1bb71c. On-hover lexicon is displayed on any scripture card that has original language on it.

**Comment by cckozie** [comment]
Works correctly in v0.9.0 build f601ed4

**Comment by cckozie** [comment]
Tested in Test Lexicon Popups
