### ISSUE TITLE
Make the feedback form a draggable modal so the user can view their work environment when reporting feedback

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#150]
Issue:
---
Currently, the feedback form is a fixed page. It should be a draggable feedback form. 

DoD:
---
The feedback form is moveable. 

Details:
---
v0.9.0 build 87451c8
The the user's project cannot be seen when submitting feedback. In many cases the feedback will be related to what is in their workspace so it would be easier for them to provide accurate feedback if they could see it when filling out the form.

**Comment by birchamp** [comment]
Workaround: Open gE in a separate tab after opening the feedback form.

**Comment by PhotoNomad0** [comment]
tCore uses ScreenDimmerContainer to gray the screen under the dialog.

**Comment by PhotoNomad0** [comment]
@elsylambert This is in GWE v1.0.0 build 68176ee.

**Comment by elsylambert** [comment]
@birchamp This is in develop v1.0. FYI.  Release label can be changed to Release 1.0.

**Comment by elsylambert** [comment]
Available  in Release Version v1.0.0 build 2e38ce6.
