### ISSUE TITLE
Column checkboxes cannot be checked after they are unchecked in tN card settings

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#168]
Issue:
---
Once a settings checkbox is unchecked it can't be re-checked except for an odd workaround.  This may be related to #165.

DoD:
---
Column checkboxes should be uncheckable and immediately re-checkable. 

Details:
---

- open tN card settings.
- uncheck any column i.e "ID" or "support reference"
Note that one you uncheck, you are unable to check them back, Unless you close and re-open settings using three-dot menu.
Or you can check it again, if you uncheck all checkboxes going up until "Books" and check then back again starting from "Books" column.![Screen Shot 2021-04-27 at 12.28.46 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/1a33b35f-9d81-4db5-9a63-657b671f5e13)

**Comment by elsylambert** [comment]
https://images.zenhubusercontent.com/310359593/e89a325d-2314-40a8-8ea1-147b4637ad5d/video_mp4__1442x890_.mp4

**Comment by elsylambert** [comment]
Works fine in v0.9.0 build 2f40ce7. Now I am able to check/uncheck columns in tN card.

**Comment by cckozie** [comment]
This is working correctly in v0.9.0 build 2f40ce7. We should have combined with #188 to get the markdown switches working correctly too.

**Comment by cckozie** [comment]
Tested in Test Persistence by User (bypassed until #216 gets fixed)

**Comment by elsylambert** [comment]
Tested in gE_Test tN column checkboxes
