### ISSUE TITLE
Card elements should not overflow the card when browser is resized

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#169]
Issue:
---
Card elements like the title and 3 dot menu will overflow the card when the user resizes the browser to a narrow width.  
DoD:
---
Card elements don't overflow the card. 

v0.9.0 build f601ed4
Currently the user is allowed to shrink the app's window width to the point where card elements are again displayed off of the card.
https://images.zenhubusercontent.com/310359593/4bbf1dd9-7346-4ee5-81eb-5ec33505954d/shrink.mp4

**Comment by mannycolon** [comment]
The layout is now persisted by breakpoints (lg, sm, xs)

Breakpoints:

- lg: 900
- sm: 680
- xs: 300

Columns:

- lg: 12
- sm: 6
- xs: 3

**Comment by cckozie** [comment]
v0.9.0 build abbbdd5
Looks good on Macbook. Need to test on Windows and with larger displays.

**Comment by elsylambert** [comment]
@mannycolon The top navigation bar is cut off when the window size is shrunk to max limit. 
![Screen Shot 2021-05-25 at 9.23.39 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/52f80bb2-c5a9-4ea5-b1a2-43c3a2c993bb) 

 To accommodate the top navigation, the window size should be increased 
![Screen Shot 2021-05-25 at 9.29.56 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/83edc3d2-8d7f-4421-8da4-db3d701ebecd)

**Comment by cckozie** [comment]
Looks good on large display and WIndows, although it seems to think there is more horizontal text because horizontal scrolling is enabled. Maybe because of Elsy's comment above? 
@birchamp - Is that something we want fixed before releasing 0.9? 
https://images.zenhubusercontent.com/310359593/a5d2849a-7d15-4ace-b4b0-3c3a824dacfa/minimize.mp4

**Comment by birchamp** [comment]
@cckozie yes this should be written up as a separate issue.

**Comment by cckozie** [comment]
I moved the problem noted to #224. Otherwise looks good.

**Comment by elsylambert** [comment]
Passing this issue as the observations are moved to #224. Card elements are not overflowing when browser is resized.
