### ISSUE TITLE
Missing Quote in tN card but the Original language is highlighted in the scripture card.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#176]
Issue:
---
Highlighting remains after looping through a TN card that has no Quote in the first record.

DoD:
---
Scripture highlighting should reflect the current Quote field in the TN record when navigating TN. 

Details:
---
Navigate to Tit 1:10
Click the TN card righthand chevron until it loops back to the first record.
Note that the highlighting from the last record remains in the scripture cards. 

Navigating through Tit project in test_org, found that Original Quote is missing, however the quote is highlighted in the scripture card.
In the content the quote is not present, so the app correctly shows it as blank but highlighted quote is confusing.
![Screen Shot 2021-04-28 at 12.09.09 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/24284897-6360-4ad7-8106-b327abf63603)

**Comment by cckozie** [comment]
Works correctly in v0.9.0 build 008141c

**Comment by elsylambert** [comment]
v0.9.0 build 008141c
The reported issue has been fixed. Not seeing highlights when the quote is empty. However, I am seeing that tN card is failing to load data for a lot of verses across a number of books, 2Jn, Romans, Philemon, Titus. Could it be related to missing quote?
Written up in #187.

**Comment by cckozie** [comment]
Tested in Test tN Clicking and Highlighing
