### ISSUE TITLE
tN card does not respond correctly after navigating to a verse with no TNs

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#184]
v0.9.0 build 008141c
Settings are English and test_org
After hitting a verse where there is no tN content, the tN card gets "stuck" showing the "Loading resource..." message. It's unclear to me what causes it to get in sync again.

https://images.zenhubusercontent.com/310359593/2cb59903-6163-4e27-a3cc-883b7602ab4a/issue_184.mp4

**Comment by elsylambert** [comment]
Similar to #187

**Comment by elsylambert** [comment]
v0.9.0 build 96e267c
tN card loads properly when the content is available. Not seeing the syncing issue.

**Comment by elsylambert** [comment]
Not seeing this issue in v0.9.0 build 96e267c. tN card loads the data correctly.

**Comment by cckozie** [comment]
Works correctly in v0.9.0 build 2f4b7ee
