### ISSUE TITLE
The tN card column checkbox settings and the view markdown switch states should be persisted (by user)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#188]
v0.9.0 build 008141c
Currently the tN card checkboxes are all set and all view markdown switches are set to off when a project is opened regardless of their state when last exited.

**Comment by elsylambert** [comment]
v0.9.0 build 66d411a
Tn card column checkboxes and Markdown switch states are persisted at user level. Works as expected.

**Comment by cckozie** [comment]
Works correctly in v0.9.0 build 66d411a

**Comment by BincyJ** [comment]
@birchamp ^^

**Comment by birchamp** [comment]
@cckozie that will need to be a separate issue if needed.  This shouldn't occur that often, but it seems like a technical hurdle.  What I would like to see is that if you set the settings for each version that you don't need to set them again even if you switch versions back and forth.

**Comment by cckozie** [comment]
@birch - So just to be clear, in your mind does the current implementation satisfies the DoD? Also, I'll defer to you to determine if something further should be written up.

**Comment by birchamp** [comment]
@cckozie I just need to know that when you set the columns for an OLD TSV, switch to a NEW TSV, change the column settings, switch back to OLD TSV. Are the settings for the OLD TSV preserved?

**Comment by cckozie** [comment]
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/ad57100c-b6aa-40a0-b72b-7094e1426c5a)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/ef970fbc-05f9-4deb-aeea-17cad24d7243)

**Comment by birchamp** [comment]
This eventuality *should* be quite rare because the conversion will be done automatically on the server.  Issue #205 addresses the inconsistency above.

**Comment by cckozie** [comment]
v0.9.0 build 2f4b7ee
The markdown switch state and column checkbox states are preserved per user.
In addition to # 205 referenced above, I wrote up #208 and #209 that are also bugs related to this issue.

**Comment by cckozie** [comment]
Tested in Test Persistence by User
