### ISSUE TITLE
Add email validation to feedback form

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gateway-edit#198]
Issue:
---
When a user enters their email address into the feedback form the email address should be checked for proper formatting as an email address in case the user mis-entered the address. The user should be notified to: "Please enter a valid email address" and prevented from submitting feedback. 

DoD:
---
Entering a malformed email address in the feedback form results in a notification and prevents the user from submitting the form.

Details:
---

**Comment by BincyJ** [comment]
TBC  how to handle missing email ID information - Need error message

**Comment by PhotoNomad0** [comment]
duplicate of https://github.com/unfoldingword/gateway-edit/issues/106
