### ISSUE TITLE
SPIKE: UI for Editing/Saving

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#200]
Users want to be able to edit resources and save them to a branch on DCS. 
For editing, users want to:
--
  * **Edit only certain fields**
     * Markdown files - TranslationAcademy and TranslationWords articles
     * In TranslationNotes OccurrenceNote, OccurrenceNumber, SupportReference, Original Quote should be editable
        * On blur the scripture highlight should update when the Original Quote or OccurrenceNumber are edited
        * On blur the TranslationAcademy article should update when the user edits the SupportReference 
     * In TranslationWord Links the Original Quote and Occurrence field should be editable

--
  * **Know what field they're currently editing:**
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/d33d8ac4-16a2-4318-afa4-6b947c3f0bf7)
--
 * **save their changes to a per user branch**
  * users should be able to click a save button to save their work
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/362877cb-2e01-48b9-8c34-8ba2a3921b48)
--
* **know when a file has been changed**
   * Each editable card should have a save icon with the tooltip "Save".
   * use https://fonts.google.com/icons?selected=Material+Icons:save for unsaved. 
   * use https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Asave for saved

--
* **switch between preview and markdown**
   * Each editable card should have a preview icon with the tooltip "Preview" when in Markdown mode and "Markdown" when in Preview mode
   * use https://fonts.google.com/icons?selected=Material%20Icons%3Apreview for formatted
   * use https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apreview for markdown
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/049b373e-fdb1-4bc3-b961-11e34e9be658)

--
 * **be notified when they can lose their changes**
  When the user can potentially lose data due to changing records or scripture references they should be notified:
A modal should inform the user of what resources have unsaved changes:
  ```
Some resources have unsaved changes that will be lost if you continue:
  TranslationAcademy
  TranslationWords

Continue without saving | Cancel | Save All
```

**Comment by birchamp** [comment]
Users want to be able to edit resources and save them to a branch on DCS. 
For editing, users want to:
--
  * **Know what field they're currently editing:**
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/d33d8ac4-16a2-4318-afa4-6b947c3f0bf7)
--
 * **save their changes to a per user branch**
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/362877cb-2e01-48b9-8c34-8ba2a3921b48)
--
* **know when a file has been changed**
use https://fonts.google.com/icons?selected=Material+Icons:save for unsaved. 
use https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Asave for saved

--
* **switch between preview and markdown**
use https://fonts.google.com/icons?selected=Material%20Icons%3Apreview for formatted
use https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apreview for markdown
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/049b373e-fdb1-4bc3-b961-11e34e9be658)



 * **be notified when they can lose their changes**
Some resources have unsaved changes that will be lost if you continue:
  TranslationAcademy
  TranslationWords

**Comment by BincyJ** [comment]
Closing this spike as add to #82
