### ISSUE TITLE
Preserve Column selections across sessions for each user.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#208]
DoD: Column selections are preserves across sessions per user. Switching TSV formats is descoped. 

v0.9.0 build 2f4b7ee
I'm not sure what steps I went through to cause this specific problem, but I documented steps in the next comment that brings a similar result.

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/b2c36243-b219-4a19-85ba-0a8ebf81fc82)

Both Annotation and Note are displayed on the card. Note is on settings modal instead of Annotation.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a399ad5b-9e74-42ba-9a35-18ce238faa46)

**Comment by cckozie** [comment]
1. Clear local storage
2. Log in and choose test_org
3. Navigate to the Account Settings page
4. Switch to test_org2
5. Note that the tN card still displays the new tsv format columns

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/af0d7b14-3631-415a-bc42-f38b4eaeb6b8)


6. Note that the tN settings modal displays the old tsv format columns
7. Check all of the unchecked column boxes
8. Note that the tN card now displays "extra" columns

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/9aaf5b62-971b-4a07-8825-31021ee31fd1)

**Comment by mannycolon** [comment]
After  [PR #213](https://github.com/unfoldingWord/gateway-edit/pull/213) TSV column filtering persistence should now only work until switching to a different TSV format

**Comment by PhotoNomad0** [comment]
> After [PR #213](https://github.com/unfoldingWord/gateway-edit/pull/213) TSV column filtering persistence should now only work until switching to a different TSV format.

@cckozie @elsylambert I presume this is an acceptable solution?

**Comment by elsylambert** [comment]
v0.9.0 build 9752842

The columns are persistent per user until the user switches TSV formats(login to a different org with an older/newer TSV format).

Not seeing the reported issue where the columns were duplicated in tN card when TSV formats were switched.

**Comment by cckozie** [comment]
The problems with the mismatched and duplicated columns after changing tsv formats has been fixed, but a new problem with settings persistence has now appeared. To replicate:
1. Clear local storage
2. Login
3. Choose test_org and English for Account Settings
4. Open the tN settings card 
5. Uncheck every-other column beginning with Chapter
6. Log out
7. Log in again using the same user as in step 2
8. Open the tN settings card and note that all columns are now checked.

https://images.zenhubusercontent.com/310359593/bd6bec73-c647-4e86-bce3-90c178db963a/issue_208.mp4

**Comment by cckozie** [comment]
@mannycolon - It appears that the differentiator here is whether or not the last column is being displayed. I'm seeing a pattern that if "Note" in the new format and "OccurrenceNote" in the old format are unchecked, then the next time the user logs in, all columns will be checked. I'm not sure this is 100% the determining factor, but so far my tests do bear it out.

**Comment by elsylambert** [comment]
@mannycolon Yes, I can confirm that. If the last column is checked, the settings are persisted for both the formats.
Thanks @cckozie for catching it.

**Comment by mannycolon** [comment]
@cckozie @elsylambert Thanks, I'll take a look at this bug.

**Comment by cckozie** [comment]
This was fixed in develop v1.0.0 build c778f02, but not in v0.9.0 build b6be351

**Comment by cckozie** [comment]
Now seeing the fix in v0.9.0 build 9b749d3 at https://release-v0-9-0--gateway-edit.netlify.app/

**Comment by elsylambert** [comment]
https://release-v0-9-0--gateway-edit.netlify.app/
v0.9.0 build 9b749d3

- Columns selection are persisted for user session.
- When TSV formats are switched, all columns are checked by default.
- Not seeing duplicated column fields display on the tN card.
- Columns are ordered alphabetically.
