### ISSUE TITLE
Tools detectable state changes of tN settings card column checkboxes and markdown view switch are delayed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#216]
v0.9.0 build abbbdd5
Katalon is unable to detect the changes of state until after a subsequent state change has occurred. e.g. If I uncheck the Book checkbox, Katalon does not detect that until I uncheck one other checkbox or change the state of the markdown view switch.

**Comment by birchamp** [comment]
@cckozie does this need to be fixed for testing 0.9?

**Comment by cckozie** [comment]
@birchamp - No, it's not necessary for 0.9. We'll just have to manually test features related to those problems.

**Comment by cckozie** [comment]
Tested in Test Persistence by User

**Comment by elsylambert** [comment]
Works fine.
