### ISSUE TITLE
Update GRT with the necessary custom hooks for editing content in gatewayEdit (useEdit custom hook)

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gateway-edit#218]

**Comment by birchamp** [comment]
Most likely an issue for @mannycolon

**Comment by mannycolon** [comment]
Should be able to test editing translation words and translation academy articles

**Comment by elsylambert** [comment]
Looks good in v1.0.0 build 1c04778.
Able to edit tW and tA articles. Working correctly as per the test notes in #263.
