### ISSUE TITLE
Create helper function to combine TSV rows/items into one file to enable editing TSV files

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gateway-edit#219]
This function needs to go in the Translation-helps RCL.

TSVs are separated into individual rows in order to navigate through them in gE.  Once they're edited they need to be combined back into a single file.  This function enables that the rows to be combined back into the file.

**Comment by mannycolon** [comment]
Pending: In Translation Word list the Original Quote and Occurrence field should be editable.

**Comment by elsylambert** [comment]
Passing this issue, Edit works fine. Tested with multiple scenarios as mentioned in the PR. For TQs not showing in unfoldingword org, this is written up in #286.
