### ISSUE TITLE
Update useRsrc hook to include the HTTP response on requests (This is needed for the useEdit custom hook)

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gateway-edit#220]

**Comment by PhotoNomad0** [comment]
@mannycolon This would not take long to do.  Do you want separate HTTP responses for the manifest and the resource fetches?

**Comment by PhotoNomad0** [comment]
@mannycolon Maybe a better question is what specific info do you need?  It may already be there but well hidden.

**Comment by BincyJ** [comment]
Manifest response to be separate.

**Comment by PhotoNomad0** [comment]
@mannycolon - fetchResponse and manifeshResponse where added with PR https://github.com/unfoldingWord/gateway-edit/pull/233.  Please verify that this meets your needs.
