### ISSUE TITLE
Network error thrown when manifest is missing for a resource 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#225]
Steps to replicate:
1. Choose "unfoldingWord " as org and "es" as language.
Note that the Message modal title shows as Network error.

![Screen Shot 2021-06-03 at 12.55.18 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/3ebceb8c-2286-4f99-b3d4-715a5065ec4a)

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie Fixed in https://develop--gateway-edit.netlify.app/, v1.0.0 build c70a6bd

**Comment by elsylambert** [comment]
Verified in v1.0.0 build c778f02 in develop branch: Not seeing the error message when the manifest is not available for a language resource.
