### ISSUE TITLE
Show the GL Quote in the TWL list

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#227]
Spike questions:
---
Because the tC logic needs to mimicked here, we need to determine what logic is tC using for determining the text to use in the "translated as" text. See [tC issue 7102](https://github.com/unfoldingWord/translationCore/issues/7102)
What will it take to make gE do this? 
 
Issue:
---
The TWL list card should show the GL quote from the resource listed in the current TW repo's manifest. To decide which resource to use for the quote gE should follow the same logic that tC follows when choosing a GL quote to display to the user. See [tC issue 7102](https://github.com/unfoldingWord/translationCore/issues/7102). The goal here is to inform users what words will be shown in the "Please select the translation for" field in tC.

![Capto_Capture 2021-06-18_09-10-08_AM.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/efb58b68-24cf-40e7-90f4-d1ae7826e2a2)
DoD:
---
The GL Quote column in the TWL list displays the aligned text that will be shown as the "translated as" text in tC.

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert - The tHelps manifest lists the GL bible that the GL quotes are based on, but it doesn't specify the organization to use. tCore always uses the D43 catalog. Do we want to do the same or do we want to check the current organization first to see if we can find it there?

And do we want to support using specific tagged version of the GL bible?  Currently tCore only uses the latest release, but we do support using specific versions of the original language bibles.

**Comment by birchamp** [comment]
@PhotoNomad0 Yes, the goal for gatewayEdit is to give teams a view of how their Book package will behave in tC once it gets published.  That way GL teams can look at what's in master, make sure that everything works and the content is correct, and then publish so the OLs can use it in tC. 

So yes, like you suggest, we need to check the current organization for the 'related' text.  If it exists then we'll pull the GL Quote from the master branch.  If it doesn't exist in the org, then we'll get it from the catalog. 
 
We'll need to allow changing versions of the text someday so yes, go ahead and make an issue for later.  tC Create is heading in that direction as well.

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert @mannycolon - Is this acceptable for showing the GL quote in the tW list view?

<img width="396" alt="Screen Shot 2021-07-27 at 10 46 05 AM" src="https://user-images.githubusercontent.com/14238574/127176851-c5c611db-c0c2-4811-a42a-7a924326bb79.png">

**Comment by mannycolon** [comment]
> @birchamp @elsylambert @mannycolon - Is this acceptable for showing the GL quote in the tW list view?
> 
> <img width="396" alt="Screen Shot 2021-07-27 at 10 46 05 AM" src="https://user-images.githubusercontent.com/14238574/127176851-c5c611db-c0c2-4811-a42a-7a924326bb79.png">
> 
> This is a capture from styleguidist demo, so there may be some slight layout differences when rendered in GatewayEdit.

Looks great to me.

**Comment by elsylambert** [comment]
@ Bruce,Looks good to me.

**Comment by PhotoNomad0** [comment]
@elsylambert - Working in v1.0.0 build 4351e56

**Comment by PhotoNomad0** [comment]
In order to see GL Quotes the tW repo must have a relation field in the manifest.  Then all the GL bibles in the relation field are loaded from the door43 Catalog.  They will be searched in the order given for alignments for that verse.  Note that none of the GLs have full alignments.  For example ru_gl/ru only has a handful of books  @elsylambert , and en is missing a lot of OT books.

**Comment by elsylambert** [comment]
1.0.0 build 1c04778. GL Quote shows up correctly in TWL list when the organization has relation field in the manifest. The highlights shows correctly for the GL Quotes for the scripture resources. When there is no alignment, the GL quote stays blank. Works as expected.

**Comment by elsylambert** [comment]
This issue did not have any points estimated. Im sure this was a great deal of work @PhotoNomad0 :)
