### ISSUE TITLE
Allow users to open more types of scripture links.

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#228]
Issue:
---
The choose version dropdown should accept links from Door43-catalog, catalog next, and scripture that is in a subfolder. 
Door43-catalog:
- [x] https://git.door43.org/unfoldingWord/en_ult
- [x] https://door43.org/u/unfoldingWord/en_ult/ - **Note** this will map to https://git.door43.org/unfoldingWord/en_ult/
- [x] https://git.door43.org/Door43-Catalog/en_ust.git
- [x] git@git.door43.org:unfoldingWord/en_ult.git

Catalog Next:
- [x] https://git.door43.org/unfoldingWord/el-x-koine_ugnt/src/tag/v0.20

DoD:
---
Users can successfully add scripture using URLs copied through the various methods of getting links from door43. 

Details:
---

**Comment by PhotoNomad0** [comment]
@elsylambert The fix is in GWE v1.0.0 build 2d0b620

**Comment by elsylambert** [comment]
Looks good in v1.0.0 build 1c04778. Able to add scriptures using the links. Not seeing the app crash when there is no scripture for a GL resource for some books, e.g ru.
