### ISSUE TITLE
Add feature to create a user branch for a resource

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gateway-edit#230]
This feature is necessary for resource editing because when a user saves an edit on a resource a user branch will need to be created.

**Comment by BincyJ** [comment]
- Need to check for user branch and if no user branch is found, then use master. If no user branch exists and user starts editing in app, user branch to be created on edit.
- If user branch exists, then display user branch at all times. User needs to be notified that it isn't master but user branch and Merge from master to user becomes necessary at this point.

**Comment by PhotoNomad0** [comment]
@birchamp @BincyJ @mannycolon  How do we initiate editing a resource?  Is this something to be selected from the card's settings menu?

**Comment by PhotoNomad0** [comment]
**Notes:**
- found how to get a list of branches at `https://git.door43.org/api/swagger#/repository/repoListBranches` (e.g. get `https://git.door43.org/api/v1/repos/test_org/en_tn/branches`)
- or to create a branch do post.

**Comment by PhotoNomad0** [comment]
@birchamp I presume we don't want to open just any branch the user may have for a repo.  Do we want to look for a specific pattern such as `username-patch-1`?  Which seems to be what DCS defaults to for edit branches.  And if there exists more than one patch, do we open the latest? @cckozie @elsylambert @mannycolon

**Comment by PhotoNomad0** [comment]
Note:

tc-create using branch name of <username>-tc-create-1

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @elsylambert @mannycolon - How do we show that they are seeing a resource in their branch?  We could show their user branch name such as:

![Screen Shot 2021-07-13 at 9 25 27 AM](https://user-images.githubusercontent.com/14238574/125460313-e87845d2-04a0-46e3-b615-db73d3aab825.png)

**Comment by birchamp** [comment]
We don't need to show it for this issue. I think it will be useful though, so I'll write up another issue to address this.

**Comment by birchamp** [comment]
The new issue is #254.

**Comment by elsylambert** [comment]
v1.0.0 build 3c9167c.
@PhotoNomad0 I have a few questions:
Details: Production server, Org-test_org2, user- elsylambert, language -en.
I edited tA on the above mentioned organization. My edits are saved. There is no indication of where is it saving the edits(Master file or my user branch?).  I want to see the DCS file to see if the edits are on the right file.How do I see my user branch/file?

**Comment by PhotoNomad0** [comment]
@elsylambert - You can look here: https://git.door43.org/test_org2/en_ta/branches

I see your edit branch on the top of the list - click the compare button to see all the changes.  That takes you to a page that shows which edits were made by gateway edit (some were made by tc-create).

**Comment by elsylambert** [comment]
Thanks @PhotoNomad0. So the branch name is ElsyLambert-tc-create-1, which is the same branch name for tcCreate app.

**Comment by PhotoNomad0** [comment]
@elsylambert Yes, that was decided by the team.

**Comment by elsylambert** [comment]
Works as expected in v1.0.0 build 1c04778. When there is no editing done at all, the user sees the master branch. As soon as the user starts to edit, there  is a branch created and edits are saved for the user branch. The branch name is username-tc-create-1 and the edits by gE can be seen separately. 

When the user branch is deleted on DCS, the user branch is lost in gE and there is no content to show for the edited resource card. When the user logs out and back in, fresh copy of the master is shown.
