### ISSUE TITLE
Separate the branch name state for each of the resources

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gateway-edit#231]
Each resource should have it's own state for the branch name so that each resource could have a different branch name if necessary

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - Working in https://develop--gateway-edit.netlify.app/  v1.0.0 build cd220a2

Currently the only thing we can test is branch support in scripture panes:  you can try using this URL for a scripture pane: `https://git.door43.org/photonomad1/el-x-koine_ugnt/src/branch/photonomad1-patch-1`.  When you navigate to tit 1:1 you will see some custom text:

<img width="470" alt="Screen Shot 2021-07-06 at 10 14 32 AM" src="https://user-images.githubusercontent.com/14238574/124616370-03edf180-de44-11eb-9303-e599c580263a.png">

**Comment by elsylambert** [comment]
Tested in v1.0.0 build 1c04778. Seeing the branch support in scripture panes as per the testing notes.
