### ISSUE TITLE
There is no highlighting in the ULT in Exodus between 11:1 and 14:11.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#236]
No highlights in the ULT either for tN's or tW's in this section. Highlights do appear for both Hebrew and the UST.
Highlights in the ULT are displayed for tN's in tC Create, and they are shown for tW's in tC, so this appears to be a problem only in Gateway Edit.

DoD:
---
Highlighting functions in Exodus 11:1-14:11 the same way it does in other scripture.

**Comment by cckozie** [comment]
Looking in developer tools I see there spans were not created for the individual words on the pane showing the ULT, so the is no way to highlight them.

This is from Exodus 1:1:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/915b09ec-d62f-42ea-b514-6283c1e64922)

This is from Exodus 14:1:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/226708c5-5ea9-455e-a7af-4b6bd37022db)

**Comment by birchamp** [comment]
@PhotoNomad0 to take a look to see what the cause is.

**Comment by PhotoNomad0** [comment]
@cckozie It looks like test_org/en does not have alignments in this section.  It works for me if I use unfoldingWord as org. @birchamp @mannycolon

**Comment by cckozie** [comment]
@PhotoNomad0 is correct. I'm closing this issue.
