### ISSUE TITLE
Handle 7-col TSV files

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gateway-edit#274]
Handle the new TSV specification allows for the reference field to have multiple references and ranges. "Handling" means that the app allows for the file to contain the references as laid out in the spec, ~~and displays the note at least once.~~

DoD:
---
Verse ranges are allowed in 7 column TSV files.

**Comment by elsylambert** [comment]
@mannycolon Not seeing the misplaced rows but the verse span remained in its original position instead of this "1:1-2 should be between 1:1 and 1:2"

**Comment by elsylambert** [comment]
After discussion with Manny, found that the note with the verse span moved to the expected row position after edits are made on the user branch. Looks good and works as expected.

**Comment by elsylambert** [comment]
Released.
