### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#283]
- Release Steps:
  - [x]  configure netlify to auto-build release branch `release-v1.0.0` (add as additional branch to Deploy contexts under https://app.netlify.com/sites/gateway-edit/settings/deploys)
  - [x]  create release branch `release-v1.0.0`
  - [x]  Ping QA that release branch is ready for testing (https://release-v1-0-0--gateway-edit.netlify.app/)

- When QA has OK'd release branch, make final release by merging to main:
  - [x] Create PR from `release-v1.0.0` branch to main branch.
  - [x] Merge pull request `release-v1.0.0` branch to main . New version is v1.0.0 build: ?\
  - [x] Ping QA that release is live at https://gatewayedit.com/
  - [ ] Final Go ahead for publish from QA
  - [x] Create & push git tag
  - [x] Publish release notes.
  - [x] Create release notes and create release on github
  - [x] Announce on forum.door43.org

**Comment by BincyJ** [comment]
https://docs.google.com/document/d/1dwZHtLiiKTzoSOQaxwNIUweJPLkIPfPs9v2SB9b9uOU/edit
