### ISSUE TITLE
TQ Resource unavailable on the card when .md files are present in the Repo

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#286]
- Found that TQ is not available for unfoldingword org even though the Repo has the .tsv files.
![Screen Shot 2021-10-14 at 1.27.29 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/e6398cd6-90ac-4973-8761-da48d6a99009)

Cleared my cache and tried again to find that TQ shows momentarily before it leave the NO content Available message.
![Large GIF (1312x926).gif](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/4b1102d7-27df-4b2a-b36f-182f2ee541ee)

**Comment by mannycolon** [comment]
TQ resource isn't shown when using a user branch

**Comment by mannycolon** [comment]
I was only able to replicate this issue by creating a new branch off of Elsy's branch using my DCS username.
