### ISSUE TITLE
Unable to save edits to TWL as it fails to add user branch.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#302]
Issue:
---
TWLs should be editable by the users. Once an edit is made and saved, the user's branch should be created and updated with the changes

DoD:
---
Users can successfully edit TWLs

Details:
---
See console for errors:![Screen Shot 2021-10-28 at 11.21.28 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/63850b8e-05d5-4bbe-81b7-ef768b3a5482)

**Comment by PhotoNomad0** [comment]
@elsylambert Do you still see this problem?  It looked like you were in Mat, so I tried editing a twl in Mat.  I am not seeing a problem.  Could you add steps to recreate the issue?

**Comment by elsylambert** [comment]
@PhotoNomad0 Not able to replicate the problem in the latest develop in QA. Moving it to watchlist.
