### ISSUE TITLE
Edits are moved to a new row(on DCS) when a new line is added in Notes/OccurrenceNotes in tN and in questions/response in tQ.

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gateway-edit#303]
The note text gets truncating when removing all the text, saving and pasting it back in the text area
Got the video from @PhotoNomad0 
https://user-images.githubusercontent.com/14238574/139467015-165b7c4b-8afd-4293-9199-88a6b4101312.mov

**Comment by elsylambert** [comment]
Just tested this issue and found that this problems happen even when a new line is added to the existing Note Text. I edited my note by adding new lines and then some text and then some new lines and saved it.
After Saving, the note did not show the edits I made, but only the existing Note Text. I checked my DCS user branch to see if the edits were saved there, but I found this error in diff:
![Screen Shot 2021-11-03 at 2.14.59 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/fa90cfab-74e4-45ac-bb90-bfd6b40ddac5)

**Comment by elsylambert** [comment]
@mannycolon I found that -
- when a new line is added in Response text area in tQ, the edits are not saved.
- when a new line is added in question text area, the response text goes blank.

**Comment by mannycolon** [comment]
@elsylambert Thank you for testing this further and adding more details on how to replicate it.

**Comment by mannycolon** [comment]
@elsylambert FYI: After this issue is fixed, if you previously encountered this bug, please remember to delete your user branches on both tN and tQ repos before retesting.

**Comment by elsylambert** [comment]
Tested in the latest build. tN edits look good when a new line is added. Edits are showing fine in the app and in the DCS file.![Screen Shot 2021-11-09 at 11.20.02 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/b769d428-8f7f-4e3f-b9a1-c23af814ba31)

**Comment by elsylambert** [comment]
In TQs, the Response field works fine both in app and the DCS repo but the question field is adding an extra "#" every time we click on the text box and on blur.
![Large GIF (822x400).gif](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ae57d4b2-9000-4a56-9af8-b7b80a245678)
Steps:
1. a. Edit the TQ question field by typing in some words.
 b. Edit the TQ question field by adding a new line. Note that the new text is not bolded.
2. Save the card after step 1.a or 1.b
3. Note that there is a # in the beginning of the sentence and on blur it stays. Click on the text box again, it adds another #.

This is the snapshot of my user branch after the edits:
![Screen Shot 2021-11-09 at 11.33.28 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ad2ef991-cb1f-442e-a2f3-8206dbc016f1)

**Comment by elsylambert** [comment]
Sorry @mannycolon TQ Question Field seems to have a new problem. See above  ^^.

**Comment by elsylambert** [comment]
v1.0.0 build 4f1f86f. Not seeing this issue in the latest build. Edits on TSV by adding a new line is working fine.
