### ISSUE TITLE
Merge Code Coverage of Cypress & Jest test results

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#306]

**Comment by PhotoNomad0** [comment]
see for help: https://dev.to/penx/combining-storybook-cypress-and-jest-code-coverage-4pa5

**Comment by mannycolon** [comment]
# Helpful Resources

- https://docs.cypress.io/guides/tooling/code-coverage#Videos
- https://github.com/bahmutov/cypress-and-jest
- https://glebbahmutov.com/blog/combined-end-to-end-and-unit-test-coverage/
- https://github.com/bahmutov/next-and-cypress-example
