### ISSUE TITLE
When TN doesn't have a reference TA should show the appropriate message

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#31]
Instead of the current message when a TN doesn't link to a TA, the TA card should display one of the following messages:
"No article is specified in the current note." (no link)
"No content available." (link exists, but can't find the article)

**Comment by mannycolon** [comment]
What tA article is General Info? Do you have a link? @birchamp

**Comment by birchamp** [comment]
@mannycolon, I misunderstood what was meant by General Information. I'm trying to get clarity on what should be put here. https://unfoldingword.zulipchat.com/#narrow/stream/214041-CONTENT/topic/UTA/near/227609265

**Comment by lrsallee** [comment]
@birchamp and I had a Zulip conversation about this (https://unfoldingword.zulipchat.com/#narrow/stream/214041-CONTENT/topic/UTA/near/227606401).

The "General Information" notes are a specific type of note that give information about a group of verses. It is not a TA topic, and not normally linked to one. Notes that do not have a tA topic should not try to display a TA topic.

**Comment by birchamp** [comment]
@mannycolon I changed the description of this.

**Comment by cckozie** [comment]
In the current build, the "No article is specified ..." message does not end with a period and the other one does. Asking for clarification from Birch on whether the current description in this issue (both messages ending with periods) is what is desired.

**Comment by birchamp** [comment]
@mannycolon @cckozie Not to be picky but it will look better to have a period at the end of "no article is specified for the current note."

**Comment by BincyJ** [comment]
According to Kos,maybe references links need to be unclickable (dead end). @birchamp

**Comment by lrsallee** [comment]
Would this be a temporary solution, until you can make the links work right? No long-term value that I can see in having links that don't work.

>According to Kos,maybe references links need to be unclickable (dead end). @birchamp

**Comment by cckozie** [comment]
v0.9.0 build edda059
@birchamp -Here is a sceenshot of the message displayed when the tA resource is not found. Is this text acceptable?
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/f0dc5363-f47a-425b-92dc-9b25cfcfc0bb)

**Comment by elsylambert** [comment]
Looks good in v0.9.0 build 4ec92f2. Seeing the message when no link is available in tN for tA.

**Comment by birchamp** [comment]
@cckozie yes that's fine. Gives the user something to check.
