### ISSUE TITLE
Minimize\Restore cards

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#319]
Users should be allowed to minimize and restore cards within the workspace.  Minimized cards should remain visible by the user so they can be restored.  Restoring the card might not necessarily go back to it’s previous place, but it will retain it’s previous size. It will be restored to the topmost place it can fit. 

https://drive.google.com/file/d/1XOHo3_VxCIgoNXVW7F51PJdyQILDCiRh/view?usp=drivesdk

DoD:
====
Users can minimize and restore cards

**Comment by mannycolon** [comment]
PENDING: Write unit tests

**Comment by elsylambert** [comment]
Works fine in v1.0.0 build 9eddfa6.

**Comment by elsylambert** [comment]
Not in Release Version v1.0.0 build 2e38ce6.

**Comment by danielklapp** [comment]
Tested with v1.1.0 build 2747aff QA. Looks good
