### ISSUE TITLE
Code/Framework overview 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#320]
Give @Joel-C-Johnson @jincypjose @PhotoNomad0 an overview of gE codebase. Review the code ahead of time prior to the overview meeting.

**Comment by birchamp** [comment]
@mannycolon please update the issue to include links/topics that need to be previewed.

**Comment by mannycolon** [comment]
# Links

- translation-helps-rcl
   - https://github.com/unfoldingWord/translation-helps-rcl
   - https://translation-helps-rcl.netlify.app/
- resource-workspace-rcl
   - https://github.com/unfoldingWord/resource-workspace-rcl
   - https://resource-workspace.netlify.app/

**Comment by birchamp** [comment]
@mannycolon just checking in to make sure this is progressing.

**Comment by mannycolon** [comment]
# Recordings

- [Part 1](https://drive.google.com/drive/folders/14HKDcciiYr0vnpffRqcndi6J-fXo_xXn?usp=sharing)
- [Part 2](https://drive.google.com/drive/folders/1q1gvIFi_WtUI32J1IhNJv3SU5a_gDNvc?usp=sharing)
- [Part 3](https://drive.google.com/drive/folders/1lxVb3b-61mVvMBkf44IwGtbQHjuTRhiG?usp=sharing)

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp - My guess is that this was completed last year.  Nothing testable here.
