### ISSUE TITLE
Original quote cut off, not wrapping

### ISSUE THREAD

**Issue by deferredreward** [unfoldingWord/gateway-edit#328]
A long original quote is cut off instead of wrapping and widening the TN box does not really help because it mainly increases spacing between fields. See screenshots.
![image](https://user-images.githubusercontent.com/703973/161272669-1528f597-bfa7-44ba-a761-981c0ddaca51.png)
![image](https://user-images.githubusercontent.com/703973/161272791-81586074-8e99-4970-a141-b17b6aca6165.png)
![image](https://user-images.githubusercontent.com/703973/161272842-ec525e22-ff73-4f9e-b7aa-2a7a12e3023b.png)

**Comment by larsgson** [comment]
Fix in translation-helps-rcl - by using MUI Autocomplete instead of HTML styled Input field (which is not multi line)

**Comment by PhotoNomad0** [comment]
Working in latest release 1.1.0

**Comment by elsylambert** [comment]
Looks good in v1.1.0 build 2747aff

[Uploading... Screenshot 2023-03-28 at 9.10.43 AM.png]
