### ISSUE TITLE
update USFM.js to fix Hebrew Punctuation issue

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#337]
Per @PhotoNomad0 the USFM.js needs to be updated in order to fix the Hebrew char issue
https://github.com/unfoldingWord/translationCore/issues/7286#issuecomment-1134684677

**Comment by PhotoNomad0** [comment]
Notes:
- actually usfm-js library

**Comment by larsgson** [comment]
@elsylambert this is now fixed in the development build

**Comment by elsylambert** [comment]
v1.0.0 build 8d822eb

**Comment by elsylambert** [comment]
Not in Release Version v1.0.0 build 2e38ce6.
