### ISSUE TITLE
Inform the user why the content isn't available

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#34]
Display an informative error about why the content isn't available. 

At least: 
The file can not be found
The file is in the wrong format
There is no associated content for this verse

**Comment by birchamp** [comment]
@PhotoNomad0 Investigate the potential reasons why content isn't available.

**Comment by PhotoNomad0** [comment]
@birchamp For scripture content failures, I found these readily identifiable conditions:
1. `Project manifest not found`
2. `Project manifest not valid`
3. `Book not found in Project`
4. `Scripture Verse not Translated`

Please tweak the above messages for comprehension.

**Comment by birchamp** [comment]
@PhotoNomad0 

1. This project manifest failed to load. Please confirm that the correct manifest.yaml file exists in the project. <repo link>
2. The manifest for this project is invalid. <repo link>
3. This book can not be found in the project. <repo link>
4. There is no associated content for this verse.

Test on slow connection to see if it creates flashing error messages.

**Comment by PhotoNomad0** [comment]
## Notes:
### for testing messages:
- in single-scripture-rcl styleguidist, in scripturePane, change HebrewExample Object
- to simulate untranslated verse, change verse to 177, should see message
- reset verse to 166 - should see verse text
- to simulate untranslated chapter, change chapter to 151, should see message
- change chapter and to 150:6 - should see verse text
- to simulate missing book, use invalid projectId, such as `psah`, should see message:
- reset projectId to `psa` - should see verse text
- test invalid organization - change resource.owner to `unfoldingWor`
- reset organization to `unfoldingWord` - should see verse text

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie Have a couple for screenshots for review:

Invalid URL:
![Screen Shot 2021-03-09 at 11 46 45 AM](https://user-images.githubusercontent.com/14238574/110507047-a8963780-80cd-11eb-8ea2-06e099b34d98.png)

Could not load manifest:
![Screen Shot 2021-03-09 at 11 42 41 AM](https://user-images.githubusercontent.com/14238574/110507253-d7141280-80cd-11eb-987b-f7fee4009934.png)

Do we want to add another error message if the URL does not match a typical DCS rep URL?

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie - Here are some tweaks for review:

![Screen Shot 2021-03-09 at 3 26 02 PM](https://user-images.githubusercontent.com/14238574/110533461-03d72280-80ec-11eb-8723-a0fad4da5f6d.png)

![Screen Shot 2021-03-09 at 3 26 40 PM](https://user-images.githubusercontent.com/14238574/110533431-ff126e80-80eb-11eb-8da7-49b088656673.png)

![Screen Shot 2021-03-09 at 3 26 58 PM](https://user-images.githubusercontent.com/14238574/110533564-1baea680-80ec-11eb-9731-98b2c8d25603.png)

![Screen Shot 2021-03-09 at 3 17 14 PM](https://user-images.githubusercontent.com/14238574/110532916-70055680-80eb-11eb-869a-8079eb900fe8.png)

![Screen Shot 2021-03-09 at 3 18 41 PM](https://user-images.githubusercontent.com/14238574/110532968-7dbadc00-80eb-11eb-9f28-3cb61faf94dd.png)

![Screen Shot 2021-03-09 at 3 20 48 PM](https://user-images.githubusercontent.com/14238574/110533016-89a69e00-80eb-11eb-8038-bff195ee1f0c.png)

![Screen Shot 2021-03-09 at 3 21 39 PM](https://user-images.githubusercontent.com/14238574/110533049-92976f80-80eb-11eb-9b8d-e795d77f58a0.png)

**Comment by cckozie** [comment]
v0.2.0 build cbad9c9
I am seeing exactly what was posted by PhotoNomad0 in the 2 immediately previous comments.
I wrote up issue #163 to point out some related issues.

**Comment by elsylambert** [comment]
Works as expected in v0.9.0 build 008141c
