### ISSUE TITLE
Account Settings ui/x behavior

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-edit#351]
The UI for the account settings page does not wait for the organizations query to complete. Thus it shows a box outlined in red.

Furthermore, since it may take a few seconds for the query to complete, it looks to the user as if it has not retained the last org selected.

In reality, the page makes the assumption that you have logged in under a different account when you go to the page and thus it must re-query to see which orgs you are a member of. Once that query is complete, the list will be shown and it your previous setting is still valid, it will set it.

This change alters the behavior to show a circular progress indicator while the query is running and will not show the settings until it is complete.

**Comment by elsylambert** [comment]
Not seeing the red outline on the org selection in v1.1.0 build 6ad4a99.
