### ISSUE TITLE
SPIKE: Find out how TWL generates the GL Quote column

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#357]
Where and how does the TWL card get the GL Quote ?
How does it know which Bible to use?
What work will need to be done to componentize this functionality so it can be used by both TSV7 TNs and TWLs?

* BCS and GeCraft want the basic functionality without all the dependencies of translation-helps. 
* Rich will need this for the TN preview/PDF 
* This should work for both a single row or multiple rows.
* Scripture lookup should follow tC's logic

Will be implemented in https://github.com/unfoldingWord/gateway-admin/issues/166

**Comment by PhotoNomad0** [comment]
**Notes:**

In Develop branch of GWE, the GL quote column is empty but scripture panes highlight the phrase aligned to the original quote:

![Screenshot 2023-01-16 at 8 57 35 AM](https://user-images.githubusercontent.com/14238574/212695883-5d68a4a6-f62e-48d0-982d-e469d0f8d421.png)

**Comment by birchamp** [comment]
Write up a **gatewayAdmin** Epic for creating and integrating a GL quote OCP Open Component Package. @mandolyte @kintsoogi

**Comment by richmahn** [comment]
@PhotoNomad0 For all of those, do we already have to make the verseObjects?

**Comment by PhotoNomad0** [comment]
![Screenshot 2023-03-13 at 1 32 19 PM](https://user-images.githubusercontent.com/14238574/224787699-5ac520cb-0da3-4d90-913b-32337cd14b3d.png)


<img width="375" alt="Screenshot 2023-03-13 at 2 03 37 PM" src="https://user-images.githubusercontent.com/14238574/224789505-b1511c18-28d6-47ac-b9ce-09471ff25804.png">

@abelpz Here are the data structures.

**Comment by PhotoNomad0** [comment]
@abelpz created https://github.com/unfoldingWord/uw-quote-helpers library as an outcome of this investigation.
