### ISSUE TITLE
GL Quotes are sometimes empty

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#358]
# Problem

The GL Quotes are sometimes empty when a previous fetch of GL Bibles returned an empty list.

# Details

Currently in translation-helps-rcl there is a check in the `useExtraContent` hook for glBibles being false, but we need to add a check for an empty array. If the array is empty, we need to re-fetch the GL Bibles.

**Comment by PhotoNomad0** [comment]
@kintsoogi Found some more detail as to why there is an empty list. Version numbers were added to the manifest relations causing a parsing error:

![Screenshot 2023-01-16 at 6 03 17 PM](https://user-images.githubusercontent.com/14238574/212777944-4b02546c-5cdc-4816-989f-42fc584e6784.png)

**Comment by PhotoNomad0** [comment]
@elsylambert FYI - see the problem of empty GL quotes in latest release and and the previous develop release using the unfoldingWord org and en.

**Comment by elsylambert** [comment]
Working fine in v1.1.0 build 6ad4a99. Not seeing empty GL quotes.

**Comment by danielklapp** [comment]
Tested with v1.1.0 build 2747aff QA. Working properly
