### ISSUE TITLE
TN card shows Book, Chapter and verse

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#363]
TN is TSV7 now, but the card shows fields for Book, Chapter and verse, Total of ten columns.

![Screenshot 2023-03-07 at 10.55.42 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c3a42193-e4e9-438c-a9a2-4ebb8e6c39e5)
![Screenshot 2023-03-07 at 10.56.36 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/f6a40788-54c6-4c86-9dbb-2d3ac7a73549)

**Comment by PhotoNomad0** [comment]
@elsylambert - I think this is intentional, so that the details of the TSV formats are hidden to the user.  To me the bigger issue would be to verify that the BCV is merged properly into TSV7 reference column when the user saves edits.

@birchamp is there a requirement to make this card look different with TSV7?

**Comment by elsylambert** [comment]
@birchamp @PhotoNomad0 Book, Chapter verse fields are not editable. In fact, there are only four fields that are editable currently: Quote, Occurrence, Notes and Support Reference.
So there will not be any issues with the merge of data to the TSV7.

**Comment by birchamp** [comment]
We will probably need to make reference editable some day.  @elsylambert can you confirm that if you turn off Book, Chapter, Verse fields that it saves that setting to the next session?

**Comment by elsylambert** [comment]
@birchamp Yes, it saves the settings to the next session.

**Comment by PhotoNomad0** [comment]
> @birchamp @PhotoNomad0 Book, Chapter verse fields are not editable. In fact, there are only four fields that are editable currently: Quote, Occurrence, Notes and Support Reference. So there will not be any issues with the merge of data to the TSV7.

Good catch - yes there is not a problem if they are not editable.
