### ISSUE TITLE
gE User Branch is not created when a card is edited if user does not have a tCCreate branch

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#364]
- Open gE app, make edits to tN card and save.
- Go to qa.door43.org/ git/door43.org and go to your branch to see the user branch. Note that the user branch is not created.

Earlier the edits were saved under user-tccreate-1 >gE edits, but if user does not have a branch in tCCreate, it cant be found.

![Screenshot 2023-03-07 at 3.16.44 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/9b5e726a-740c-40ec-9be4-82acf57b3e2f)

![Screenshot 2023-03-07 at 3.16.58 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/64e9dddd-e7e6-4404-8973-ff7803a1eeb7)

**Comment by PhotoNomad0** [comment]
@elsylambert The console logs are interesting - it looks like the URL is not pointing to QA server.

**Comment by PhotoNomad0** [comment]
@elsylambert It seems to be working on develop branch on qa server `v1.0.0 build 8d822eb QA`.  Are you testing with the release?

**Comment by PhotoNomad0** [comment]
@elsylambert Trying again here - misread the steps.

**Comment by elsylambert** [comment]
Discussed with Bruce and found out that I was looking at the qa server for the branch, but I was editing on the production link (forgot to parametrize the URL ?server=qa). It works correctly after I toggled the correct server.
