### ISSUE TITLE
Quote Field is not populated correctly when Notes are navigated.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#368]
v1.1.0 build 6ad4a99.
-Navigate through the Notes and Note that the Quote remains the same however the highlights in the scripture pane changes.
![Screenshot 2023-03-15 at 2.45.08 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/7d930633-2873-4654-86da-4ba2ac4e7bfb)

https://images.zenhubusercontent.com/310359593/0d7110c7-ad12-4fd4-8b6e-1abc3e6610ea/screen_recording_2023_03_15_at_2_48_13_pm.mov

Case II: Edit the Quote and Save. Note that it is not saved at first.
https://images.zenhubusercontent.com/310359593/c2ab5dff-9c31-4b7b-9992-45ffd403753e/screen_recording_2023_03_15_at_2_48_52_pm.mov

**Comment by PhotoNomad0** [comment]
@elsylambert The for this is in the 1.1.0 RC at: https://release-v1-1-0--gateway-edit.netlify.app/

**Comment by elsylambert** [comment]
This issue is resolved in v1.1.0 build 2747aff. Quotes are displayed fine when Notes are navigated. Not seeing the issue in saving the note as well.

**Comment by danielklapp** [comment]
Tested with v1.1.0 build 2747aff QA. Working properly
