### ISSUE TITLE
TranslationWord highlighting

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#37]
When a user clicks in a TW card the current aligned word(s) should be highlighted in the scripture pane.

**Comment by mannycolon** [comment]
## Research

- https://github.com/unfoldingWord/single-scripture-rcl/blob/main/src/hooks/index.tsx
- https://github.com/unfoldingWord/scripture-resources-rcl/blob/868caad33e9979b19cf4d7ff4e36169174871df9/src/components/verse-objects/VerseObject.js#L14
- https://github.com/unfoldingWord/scripture-resources-rcl/blob/868caad33e9979b19cf4d7ff4e36169174871df9/src/components/verse-objects/AlignedWordsObject.js#L30
- https://github.com/unfoldingWord/scripture-resources-rcl/blob/868caad33e9979b19cf4d7ff4e36169174871df9/src/components/selections/helpers.js#L63
- https://github.com/unfoldingWord/scripture-resources-rcl/blob/868caad33e9979b19cf4d7ff4e36169174871df9/src/components/selections/helpers.js#L46
