### ISSUE TITLE
Add Word Aligner and Scripture Edit to GWE

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#372]

**Comment by PhotoNomad0** [comment]
@elsylambert See Epic for more info.  This is now live in the GWE develop branch (but not in 1.1.0 release)

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp My intent is to make this available for review.  Still may be work to improve the UI.  For that we an start attaching issues to the EPIC (I converted SPIKE to an EPIC).

**Comment by PhotoNomad0** [comment]
@elsylambert edit and alignment is now working  in latest develop build `v1.2.0 build 1f1cfb01`

**Comment by elsylambert** [comment]
@PhotoNomad0 Please see the screen recording, the edits are not saved properly.

**Comment by elsylambert** [comment]
Issue 2: after the verse is edited and alignment is broken, I opened the Aligner and aligned the work from the word bank and clicked on Accept and then Saved it. Note that the alignment is still broken and changes are not saved.

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 Please see the screen recording, the edits are not saved properly.
> 
> https://images.zenhubusercontent.com/310359593/178bf739-e6ad-4a9a-aeb4-872fbf39c492/screen_recording_2023_04_06_at_9_25_29_am.mov

@elsylambert Great catch!  I think I have always been clicking off the edit before saving.

**Comment by PhotoNomad0** [comment]
@elsylambert fixing some race conditions.

**Comment by PhotoNomad0** [comment]
@elsylambert - save fix is in  GWE `v1.2.0 build 5ae2f49`

**Comment by danielklapp** [comment]
Looks like it's working properly with v1.2.0 build 84f7e6f QA.

**Comment by elsylambert** [comment]
Word Aligner and scripture editing looks good in v1.2.0 build b660927 QA. Not seeing issues in saving to user branch. Currently it saves in tCCreate branch, should save in the new format after
