### ISSUE TITLE
Add support for reference ranges to show multiple verses in the scripture panes

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#374]
decouple scripture panes from bible-reference-rcl - the reference in the current tNote takes priority for the scripture reference(s) shown  

DoD
---
Single Scripture RCL will have a styleguidist example that proves it supports reference ranges. 

Details:
---
Lars may have something working this way already.

**Comment by PhotoNomad0** [comment]
Notes:
-  in Scripture card the reference is parsed into an array `scriptureConfig?.versesForRef` that looks like:
- can change Scripture card to display a vertical array of scripture panes - one for each array element of `scriptureConfig?.versesForRef`.

**Comment by birchamp** [comment]
@kintsoogi note that, verse spans are multiple verses marked as a single verse in USFM scripture as \v 2-3 followed by the text of the two verses mixed together.

Reference ranges is any reference that refers to more than one verse. Reference ranges don't include any scripture. It's just the reference.

**Comment by PhotoNomad0** [comment]
> Notes:
> 
>     * in Scripture card the reference is parsed into an array `scriptureConfig?.versesForRef` that looks like:
> 
> 
> <img alt="Screenshot 2023-03-28 at 6 34 59 AM" width="294" src="https://user-images.githubusercontent.com/14238574/228213004-3baa4c6b-6b81-4917-966b-13d8fd7b307b.png">
> 


@kintsoogi  Also there may be and endVerse in the array object if there is a verse span included in the ref range.

**Comment by PhotoNomad0** [comment]
@kintsoogi Sorry - that was incorrect.  A verse range will look like this (easier):

<img width="335" alt="Screenshot 2023-03-28 at 7 44 41 AM" src="https://user-images.githubusercontent.com/14238574/228226010-b061c63e-1fd9-4f89-9c02-37e277e24894.png">

**Comment by Joel-C-Johnson** [comment]
**test procedure**
 - the fixes are in gatewayEdit in v1.2.0 build 9ebcb5b
 - test in unfoldingword org - en - PHP - 1:15 
 - open tcCreate production - unfoldingword org - -tN- en - PHP - 1:15 
 - edit the first note and change the reference to 1:14-18 and put some Greek words in the quote
  
 screenShot 1
![image](https://user-images.githubusercontent.com/25791348/229837166-e005024e-6de6-4438-98a9-a7c3793a6ca4.png)

- save the changes
- open [gatewayedit](https://develop--gateway-edit.netlify.app/) 
- select unfoldingword org - en - PHP - 1: 15 and you should see all the verses from 14 to 18 such as below.
screenshot 2
![image](https://user-images.githubusercontent.com/25791348/229839077-81548bc3-281b-426c-8ddd-67d0d5ccae74.png)

@elsylambert

**Comment by elsylambert** [comment]
Looks good in v1.2.0 build 9ebcb5b

**Comment by danielklapp** [comment]
Looks good with v1.2.0 build 1f1cfb0 QA
