### ISSUE TITLE
change card rendering - any tNote check whose reference contains the current bcv will be included in the tN cards for current verse

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#375]
(see useTsvItems.getTsvItems() in tHelps-rcl).

The card and current item that is in focus determines what is shown in the scripture pane.

DoD:
---
If the user chooses a verse that has a TNs with a reference range that includes that verse, that TN will be displayed.

Details:
---
Chris H and Abel did similar lookup work in tCC.

**Comment by PhotoNomad0** [comment]
Notes:
- it looks like the fix needs to be in  useTsvItems.getTsvItems() in the tHelps-rcl.
- also will have to pull in  `bible-reference-range` which has a method doesReferenceContain() that can be used to see if current chapter:verse is contained in the ref which could be a reference range.

**Comment by Joel-C-Johnson** [comment]
**test procedure**
 - the fixes are in gatewayEdit in v1.2.0 build 9ebcb5b
 - test in unfoldingword org - en - PHP - 1:15 
 - open tcCreate production - unfoldingword org - -tN- en - PHP - 1:15 
 - edit the first note and change the reference to 1:14-18 and put some Greek words in the quote
  
 screenShot 1
![image](https://user-images.githubusercontent.com/25791348/229837166-e005024e-6de6-4438-98a9-a7c3793a6ca4.png)

- save the changes
- open [gatewayedit](https://develop--gateway-edit.netlify.app/) 
- select unfoldingword org - en - PHP - 1: 15 and you should see all the verses from 14 to 18 such as below.
screenshot 2
![image](https://user-images.githubusercontent.com/25791348/229839077-81548bc3-281b-426c-8ddd-67d0d5ccae74.png)

@elsylambert

**Comment by elsylambert** [comment]
Looks good in v1.2.0 build 9ebcb5b

**Comment by danielklapp** [comment]
Looks good and is working properly. Tested with v1.2.0 build 1f1cfb0 QA.
