### ISSUE TITLE
Fix tn and twl that they trigger scripture pane to show all verses in verse ranges/lists

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#376]
The card and current item that is in focus determines what is shown in the scripture pane.

DoD:
---
When the user browses the TN or TWL card, the scripture pane updates what verse or verses are shown based on whether there is a reference range.

**Comment by PhotoNomad0** [comment]
Notes:
- it looks like the fix needs to be in  useTsvItems.getTsvItems() in the tHelps-rcl.
- also will have to pull in  `bible-reference-range` which has a method doesReferenceContain() that can be used to see if current chapter:verse is contained in the ref which could be a reference range.

**Comment by elsylambert** [comment]
Looks good in v1.2.0 build 9ebcb5b

**Comment by danielklapp** [comment]
Looks good with v1.2.0 build 1f1cfb0 QA
