### ISSUE TITLE
Fix lexicon popups

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#384]

**Comment by danielklapp** [comment]
Looks good with v1.2.0 build 84f7e6f QA.

**Comment by elsylambert** [comment]
v1.2.0 build b660927 QA. It shows Lexicon not ready yet.
![Screenshot 2023-04-19 at 6.48.04 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/e1e01a84-5dfb-416d-a34b-21f1754e8b90)
