### ISSUE TITLE
Support alignment for multiple verses in SP

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#385]
This seems to be mostly implemented, but need UI design for how we implement selecting which verse or verse span in reference range to align.  Elsy suggested at one point to have an icon button on Scritpure card title that opens drop down for selecting the verse to align.  But Currently GWE uses a pop up dialog for three dot settings.  Maybe we could also do a pop up dialog to select which verse to edit if there is more than one in the scripture card.

**Comment by PhotoNomad0** [comment]
Notes:
- to put alignment icon on scripture card do:

```
  const checkingState = aligned ? 'valid' : 'invalid'
  const titleText = checkingState === 'valid' ? 'Alignment is Valid' : 'Alignment is Invalid'
  const onRenderToolbar = ({ items }) => [
    ...items,
    <IconButton
      className={classes.margin}
      key='checking-button'
      onClick={() => handleAlignmentClick()}
      title={titleText}
      aria-label={titleText}
      style={{ cursor: 'pointer' }}
    >
      {checkingState === 'valid' ? (
        <RxLink2 id='valid_icon' color='#BBB' />
      ) : (
        <RxLinkBreak2 id='invalid_icon' color='#000' />
      )}
    </IconButton>,
  ]
```

**Comment by birchamp** [comment]
@birchamp Mock up a solution for picking a verse.

**Comment by danielklapp** [comment]
User can easily select which verse or verse span to align in the pop up dialog. This feature looks good! Tested with v2.0.0 build e6d6a7f QA.
