### ISSUE TITLE
Format TQ question and answer

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#39]
Question is large and bold and answer is normal text

**Comment by cckozie** [comment]
Looks good in v0.2.0 build cbad9c9

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/951eeac5-6953-4bd7-aed1-90c411751b82)

**Comment by mannycolon** [comment]
@birchamp Does the markdown have to follow your instructions to a T? I thought this was just a temporary fix before we got the new tQ TSV format?

**Comment by birchamp** [comment]
@mannycolon that's correct. The description was a temporary workaround

**Comment by BincyJ** [comment]
The permanent solution involves a new tsv format for tQ.

**Comment by elsylambert** [comment]
Can we discuss this tomorrow ,cckozie ?

**Comment by elsylambert** [comment]
v0.9.0 build 4ec92f2
TQ card with the new TSV format: The question is large and bold and answer is normal text.
![Screen Shot 2021-04-19 at 10.20.30 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/d96141b7-0a00-4074-a576-c604f0bf350a)

Passing this issue based on our discussion that this format is fine as of now.
