### ISSUE TITLE
Examples from the Bible stories reference links don't load anything. 

### ISSUE THREAD

**Issue by danielklapp** [unfoldingWord/gateway-edit#391]
v1.1.0 build 2747aff QA
In tW article under Examples from the Bible stories - when clicking on any reference links for a split second it shows loading but never loads anything.

**Comment by danielklapp** [comment]
@kintsoogi thanks, I'll retest and provide examples.

**Comment by danielklapp** [comment]
@kintsoogi I've retested with the https://release-v2-1-0--gateway-edit.netlify.app/ link v2.1.0 build f43bad3 QA and here’s the steps I took.

- Opened  Matthew  1:1
- Went to translationWords Article and scrolled down to Examples from the Bible stories: 
- when clicking on any reference links for a split second it shows loading but never loads anything.

https://github.com/unfoldingWord/gateway-edit/assets/82067076/8998de7b-5bb2-490b-af71-7ace6db94bbf

**Comment by danielklapp** [comment]
I also discovered that above Examples from the Bible stories: the links under Bible References: gives 404 error.

<img width="1433" alt="Screenshot 2023-07-26 at 2 20 35 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/cd810df4-5591-4065-a4ad-69bf22e52b58">

**Comment by Joel-C-Johnson** [comment]
- Need to work on translation-help-rcl
- find the URL/Links path is wrong (When we click on the links it directs us to 
`GET | https://git.door43.org/api/v1/repos/unfoldingWord/en_obs-tn/contents/content/46/06.md?ref=master`. 
- there is no directory in - [door43](https://git.door43.org/unfoldingWord/en_obs-tn)

**Comment by Joel-C-Johnson** [comment]
Connected RCL's - 
- [translation-help-rcl](https://www.npmjs.com/package/translation-helps-rcl)
  (for card content)
- [resource-workspace-rcl](https://resource-workspace.netlify.app/#workspace)
 (for card styles, dragable cards etc )
- [single-scripture-rcl](https://single-scripture-rcl.netlify.app/#section-scripturecard)
(for scripture card)

**Comment by elsylambert** [comment]
v2.1.0 build ad1df2f QA Examples from the Bible stories reference links are loading content from OBS. Looks good.

**Comment by danielklapp** [comment]
Links are loading OBS content. Looks good to me and tested with v2.1.0 build ad1df2f QA.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3crIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--428e57573205831a4b349d61029be4b212e8afca/Screenshot%202023-08-25%20at%202.56.21%20PM.png)
