### ISSUE TITLE
Implement quote highlighting in ScripturePanes for reference range

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#395]
based on the Spike #357
This will require Abel's quotes rcl to implement

**Comment by danielklapp** [comment]
Seeing highlighting in the ScripturePanes for reference range.Tested with v2.0.0 build 2c0eca3 QA.

**Comment by elsylambert** [comment]
Looks good in v2.0.0 build a2a20c1 QA. Highlights are seen in a reference range.![Screenshot 2023-04-25 at 9.52.21 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/571cbce6-ea41-4213-8e3f-aaba8863b561)
