### ISSUE TITLE
In some cases, alignments still show as incomplete in word aligner even after all alignments are finished

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#397]
In en_ust, unfoldingWord, PHP 1:15-17 - open word aligner and complete the alignments by merging unaligned greek words with other alignments.  When finished, the alignment icon still shows broken.

**Comment by PhotoNomad0** [comment]
@elsylambert This is fixed in latest develop v1.2.0 build 26c1bbf

**Comment by danielklapp** [comment]
Works properly with v1.2.0 build 84f7e6f QA.

**Comment by elsylambert** [comment]
v1.2.0 build b660927 QA, Seeing some issues :
I. In en_ust, unfoldingWord, PHP 1:15-17 , after aligning the Greek Words, Clicked on the Accept button>The aligner screen is hung up. Click on Cancel> Nothing happens. I had to kill the session. ![Screenshot 2023-04-19 at 6.06.56 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/727b08b0-5443-4480-a6bc-ca5871d94373)



Issue II: In en_ust, unfoldingWord, PHP 1:15-17 , after aligning the greek words, not seeing the broken link icon.
- Edit the verse > save. The broken link icon shows up. Open the Aligner and drag the new edits to complete the alignment. Click on Accept.
- On the scripture card, Click on save. Note that edits and alignment link looks fine.
- Click on the same verse to edit and remove the edits done in step 2. Note that the alignment link is not broken.
- Open the aligner and note that it looks fine. Click on Accept on the Aligner. Note that the verse shows Null with alignment broken.
![Screenshot 2023-04-19 at 6.09.44 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/37196984-7a44-4c72-a6c4-adaa763bc701)
![Screenshot 2023-04-19 at 6.10.01 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/bbb31a43-588f-43cd-9a71-86dc82e48bc7)

**Comment by elsylambert** [comment]
Separated the bug in #424 for the Alignment screen going Null.
For the above issue, Alignments when completed the icon shows completed, so Passing this issue.
