### ISSUE TITLE
Adding merge status and merging to GWE

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#399]
**Notes:**
- make use of https://github.com/unfoldingWord/dcs-branch-merger
- see examples at https://unfoldingword.github.io/dcs-branch-merger

**Phases:**
1. integrate with icon buttons on resource/scripture cards
2. move icon buttons to app with drop down to select cards to update.  (perhaps make use of app context?)

Notes:
---
The tCC epic https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/gh/unfoldingword/tc-create-app/1566 should inform how gatewayEdit handles merging.

**Comment by elsylambert** [comment]
@PhotoNomad0 Can you take a look if this is merged to master branch?

**Comment by PhotoNomad0** [comment]
> Bug #1: On save of resource or scripture, Header and Drawer buttons are caught in endless loading Bug #2: Sometimes two pull requests are created when calling mergeToMaster. Is this a lifecycle issue of calling it twice?

@elsylambert It looks like @kintsoogi found two additional problems with the work already merged, so this is not yet ready.

**Comment by elsylambert** [comment]
Looks good in v2.1.0 build 66dd56e QA.

**Comment by danielklapp** [comment]
Everything working properly. Tested with v2.1.0 build 66dd56e QA.
