### ISSUE TITLE
Support Book edit branches for Scripture cards.

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#400]
Issue:
---
Scripture should be saved to the same branch that gatwayTranslate is using. `auto-<user>-<bookid>`

Edit: and bookId is in upper case.

Details:
---
gT uses a book-user branch. gE uses tCC style branches. This will mean that the same scripture can be edited by the same user in two different branches.  Is there a compelling reason to go to book user branches?

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This issue is included in GWE v2.0.0 build 04b4863

**Comment by danielklapp** [comment]
The branch I created comes up as "auto-danielklapp-MAT", so new branches are the same format as gatwayTranslate.  Tested with v2.0.0 build 14ef565 QA. Looks good
