### ISSUE TITLE
Remove merge button from cards and make a menu item. 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#409]
when merging, prompt user for which resource they want to merge.

**Comment by PhotoNomad0** [comment]
Note:
- Need to more share to master into hamburger menu. Add multi-select for user to select which cards to share. Each card entry should show sync state such as needs merge or merge conflict.

**Comment by danielklapp** [comment]
Looks good to me. Tested with v2.1.0 build 66dd56e QA.

Merge button has been removed from cards and placed into hamburger menu. Listed as Merge my work. After user clicks it, a merge pop up window appears and user is able to select which cards to merge.

<img width="1433" alt="Screenshot 2023-07-27 at 9 58 16 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/6eef05e1-938a-48a6-9486-2278a168afd3">

After user clicks submit to merge their desired mergeable resource or resources, a Cards Sync Feedback pop up appears showing sync state.

<img width="1440" alt="Screenshot 2023-07-19 at 2 07 02 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/de72c9c4-cdf7-476d-80b0-787f9d2755a7">
