### ISSUE TITLE
Move app level update button to far right 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#410]
Need to move sync icon button into header. Add multi-select for user to select which cards to sync. Each card entry should show sync state such as needs merge or merge conflict.

**Comment by theNerd247** [comment]
fixed in v2.1.0 build e3fb05f

**Comment by danielklapp** [comment]
The update my content icon has been moved to the far right corner of header. Tested with v2.1.0 build ab322f9 QA.

<img width="1435" alt="Screenshot 2023-06-13 at 4 53 16 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/5f88f763-c380-4837-8c40-10f1f6b5456d">

**Comment by elsylambert** [comment]
Looks good in v2.1.0 build 66dd56e QA. Update content button is found on top right in the blue header and works fine.

**Comment by danielklapp** [comment]
Also looks good to me in v2.1.0 build 66dd56e QA.
