### ISSUE TITLE
Bug Word Aligner sometimes will not close after lexicon popups are opened.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#413]
Need to determine why this happens and resolve.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp I can no longer reproduce this in GWE v2.0.0 build 2ffa47f - so I think this is fixed.

**Comment by elsylambert** [comment]
Not seeing this issue  in v2.0.0 build c8df80d QA at https://release-v2-0-0--gateway-edit.netlify.app/

**Comment by danielklapp** [comment]
Agree that word aligner closes after lexicon popups are opened. Tested with v2.0.0 build e8a3884 QA.
