### ISSUE TITLE
IDs for Floating Action Button items

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#416]

**Comment by birchamp** [comment]
Work with Daniel on finding missing IDs.

**Comment by danielklapp** [comment]
Restoring minimized cards
Parent container (<div class="jss28">) to have good meanful ID that makes it unique.
Child containers (<div class= "jss29">) to have CSS class names of what components they are.
Total of eight child containers: 
Literal Translation
Original  Source
Simplified Translation
translationNotes
translationAcademy
translationWords List
translationWords Article
translationQuestions

**Comment by jincypjose** [comment]
(WIP)These are the id's to click on
show_minimized_cards
close_minimized_cards
restore_button_resource_card_tq for Translation questions
restore_title_resource_card_tq for Translation questions
restore_title_scripture_card_Literal_Translation for Literal Translation
restore_button_scripture_card_Literal_Translation for Literal Translation
restore_title_scripture_card_Original_Source for Original Source
restore_button_scripture_card_Original_Source for Original Source

**Comment by jincypjose** [comment]
@danielklapp @elsylambert the fixes are in https://release-v2-0-0--gateway-edit.netlify.app
version- v1.2.0 build b660927

**Comment by danielklapp** [comment]
@jincypjose IDs for buttons is looking Great! 
I've noticed it would be helpful to add IDs to the alignment buttons that specific to Literal Translation card, Original Source card, and Simplified Translation card.

**Comment by PhotoNomad0** [comment]
> @jincypjose IDs for buttons is looking Great! I've noticed it would be helpful to add IDs to the alignment buttons that specific to Literal Translation card, Original Source card, and Simplified Translation card.

We need to talk about this, since the scripture cards are not fixed, they can be swapped or changed point to about any scripture repo.

**Comment by PhotoNomad0** [comment]
Also in the resource-workspace-rcl we have:

id="restore_title_scripture_card_Original_Source"
id="restore_button_scripture_card_Original_Source"

**Comment by PhotoNomad0** [comment]
To fix the title, in single-scripture-rcl ScriptureCard change
```
        onMinimize={onMinimize ? () => onMinimize(id) : null}
```
to be
```
        onMinimize={onMinimize ? () => onMinimize(id, scriptureLabel) : null}
```

And in resource-workspace-rcl useMinimizedCardsState,

- add a state variable to persist titles `const [minimizedCardTitles, setMinimizedCardTitles] = useUserLocalStorage('minimizedCardITitles', {});`
- need to add a title as second parameter to ` const minimizeCard = (id) => {`
- and in the function add the title to `minimizedCardTitles`
- and need to change `minimizedCards` declaration to be a useMemo and return items that match contained in `minimizedCardIds` and replacing the titles if contained in `minimizedCardTitles`

**Comment by jincypjose** [comment]
@Joel-C-Johnson i have did what need have to be done in ScriptureCard.tsx as bruce metioned above. Now the WorkspaceContainer.js need to be fixed with cardNum.

**Comment by danielklapp** [comment]
@Joel-C-Johnson can you give an update about the changes you’ve made and how we can test those changes?

**Comment by Joel-C-Johnson** [comment]
Hi @danielklapp, I will right the steps here and if you have doubts please ping me on Discord.
**1. Login into gatewayedit - https://gateway-edit.netlify.app/
2. Open inspect and click on each card using the "pick element tool"**

![image](https://github.com/unfoldingWord/gateway-edit/assets/25791348/6c610aa8-63a3-4d76-b954-40f7f62249a7)

**3. You can able to see unique id's for cards and icons
4. Minimize cards using the '-" icon in the cards
5. you can able see recent cards on the right side** 

![image](https://github.com/unfoldingWord/gateway-edit/assets/25791348/aee13ae7-2f97-4006-9eac-6abd341faed7)

**6. click on it and you can see the list of cards with unique id and names**

![image](https://github.com/unfoldingWord/gateway-edit/assets/25791348/fad71afa-283d-4f56-83f3-8a9e5992ea39)

**Comment by danielklapp** [comment]
@Joel-C-Johnson thanks, just wanted to make sure my testing covered all work you guys did.

**Comment by elsylambert** [comment]
Looks good in v2.1.0 build 66dd56e QA. Seeing IDs in Restore card button icons.

**Comment by danielklapp** [comment]
Looks good to me. I see unique IDs for all the buttons listed. Tested with v2.1.0 build 66dd56e QA.
