### ISSUE TITLE
Aligner window can be dragged off the screen.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#419]
Aligner window is draggable which is good, but it should not go beyond the workspace area. 
Given that the user has the alignment window open
When the user drags the alignment window
Then the user should be prevented from dragging the window completely out of view.  At least a margin of 30 pixels wide should be showing at all times. 

![Screenshot 2023-04-19 at 6.44.20 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/9675269f-5808-4b5a-8158-22f7ba6a9a87)

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This issue is in develop branch v2.3.0 build a9a318b

**Comment by danielklapp** [comment]
The user is prevented from dragging Aligner window completely out of view. Looks good and tested with v2.3.0 build 0eda053 QA.

<img width="1439" alt="Screenshot 2023-12-20 at 11 38 54 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/7f2ca597-ce5a-4f48-b3a0-726264c7765f">

**Comment by elsylambert** [comment]
Works as expected in v2.3.0 build 0eda053 QA.
