### ISSUE TITLE
Incorrect title on scripture card restore button.

### ISSUE THREAD

**Issue by danielklapp** [unfoldingWord/gateway-edit#421]
Testing with v1.2.0 build b660927 QA.
Steps to create scenario:

1. Go to Simplified Translation scripture card and click menu button.
2. When menu setting card pops up choose Literal Translation.

![Screenshot 2023-04-20 at 5.08.18 PM.png](https://images.zenhubusercontent.com/63e2b3aebe65b0eb5b78a45f/84448af9-dc32-4439-9f12-f7faccdc293b)

3. Click out of menu setting and minimize the newly selected Literal Translation scripture card.
4. After clicking on recent cards notice that the title on restore button still says Simplified Translation.

![Screenshot 2023-04-20 at 5.11.49 PM.png](https://images.zenhubusercontent.com/63e2b3aebe65b0eb5b78a45f/1daab513-7cc8-4b02-976f-88ae9b3952b1)

**Comment by elsylambert** [comment]
@danielklapp Can you retest this one in the latest develop?

**Comment by danielklapp** [comment]
I've retested in the latest develop v2.1.0 build e2d994b QA. Restore title does match with the correct scripture card title. Looks good to me.
