### ISSUE TITLE
Aligner shows null values when reopened and Accepted 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#424]
v2.0.0 build a2a20c1 QA.

Aligner screen goes blank with null values when it is fully aligned and user Clicks on Accept.
Steps to replicate:
- Click on the Alignment link icon, It opens up the aligner screen or a list of verses(in case of Reference ranges, choose the verse). 
- If the alignment is all complete, click on Accept. Note that the Broken alignment link is shown for that verse.
- Open the Aligner again and note that the screen has null values.

Note: It works fine if user clicks on Cancel button instead of Accept.![Screenshot 2023-04-25 at 11.01.07 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/942347af-1238-4a0b-a142-693ef52f0191)![Screenshot 2023-04-25 at 11.08.47 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/1a0f0c42-bc63-46ee-9e74-5e37622ba128)

https://images.zenhubusercontent.com/310359593/2f880541-dfa2-4d7f-8344-e1f784a223ad/screen_recording_2023_04_25_at_11_17_27_am.mov

**Comment by elsylambert** [comment]
@kintsoogi looks good in the deploy preview link. Not seeing the Aligner going blank on switching between verses or scriptures.

**Comment by danielklapp** [comment]
Looks good, that seems like it fix the problem. Tested with v2.0.0 build ee140bd QA.

**Comment by PhotoNomad0** [comment]
@danielklapp This was in the review column, but it looks like you approved it so I moved it to `in QA` since I am not certain where it should go. @elsylambert

**Comment by danielklapp** [comment]
@PhotoNomad0 We did approve it, and shortly after kintsoogi and Abel discovered that the verse and alignment data wasn’t updating correctly on book & chapter select. We decided to put it back in review column since that bug was introduced after the fix. I'll take another look at it.

**Comment by PhotoNomad0** [comment]
@danielklapp OK that is a confusing case.  But I would suggest that QA fail would be a better spot to draw attention to something being broken.

**Comment by danielklapp** [comment]
@PhotoNomad0 Ok that’s good to know, thanks. After testing several times with v2.1.0 build 5c24985 QA it seemed to work fine. Last time testing in case of reference ranges I was able to recreate the failed scenario. Maybe we can move it to our QA Watchlist @elsylambert.

**Comment by elsylambert** [comment]
Not seeing this issue in v2.0.0 build c8df80d QA at https://release-v2-0-0--gateway-edit.netlify.app/. so Passing this issue.

**Comment by danielklapp** [comment]
I figured out a scenario to recreate the aligner showing null values after reopened and accepted. It happens after messing with the list of verses in reference range. Then right after go to a single verse outside of reference range, click aligner button and just accept. The verse turns to null and then everything in aligner is null. Here’s a video of that. I'm testing with v2.0.0 build c8df80d QA. 



https://github.com/unfoldingWord/gateway-edit/assets/82067076/2a905d27-001e-4cd9-ab95-1a18b0cf950e

**Comment by danielklapp** [comment]
@kintsoogi after your merge I'm not seeing this issue anymore. Looks like that fixed it. Tested with v2.0.0 build e8a3884 QA.
