### ISSUE TITLE
Verse and alignment data not updating correctly on book & chapter select

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#427]
Book and Chapter navigation select are no longer working properly. When a user navigates to another book or chapter using EITHER the book/chapter autocomplete selector OR the double arrows (used to switch chapters) the verse and alignment data remains the same from the previous reference. 

STEPS TO REPRODUCE

- [ ] Start in any reference

![image](https://user-images.githubusercontent.com/118755839/234684667-195c28a3-ab54-45da-b755-09806aa69995.png)

- [ ] Click the Book selection drop box and select another book

![image](https://user-images.githubusercontent.com/118755839/234684883-bf9df2af-4285-4755-bffc-27b44ebba6fd.png)

- [ ] Observe that verse data and alignment data has stayed the same from previous reference

![image](https://user-images.githubusercontent.com/118755839/234685098-37759f8c-c14d-4d89-a0c8-036529a05726.png)

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This is now working in v2.0.0 build 04b4863

**Comment by elsylambert** [comment]
Looks good in v2.0.0 build 04b4863 QA at https://release-v2-0-0--gateway-edit.netlify.app/.
Not seeing the issue. When the Book/Chapter /verse is selected from the top navigation, the scriptures are updated correctly.

**Comment by danielklapp** [comment]
Top navigation working properly when selecting scripture by book/chapter/verse. Tested with v2.0.0 build 14ef565 QA. Looks good
