### ISSUE TITLE
Unless overridden point localhost and develop URLs to QA

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-edit#429]
Problem: Currently, even running locally points to production DCS by default. This makes it too easy to mistakenly do things against production data.

Solution:
- If the server parameter is specified use it (no matter the URL)
- Otherwise, if URL includes the strings "localhost" or "develop" or "deploy-preview", then point to QA DCS.

**Comment by mandolyte** [comment]
Note: originally I tried to set the default server value in Layout.js where the server parameter is processed. This did not work.

It is now relocated to the auth context, where the default is set as soon as the window variable becomes available on the client side.

**Comment by theNerd247** [comment]
Hey @Joel-C-Johnson @PhotoNomad0 is this issue closed since #428 was merged?

**Comment by danielklapp** [comment]
The different develop and deploy preview links I tested with pointed to QA server and not Prod. One of the links I tested with was https://develop--gateway-edit.netlify.app/ and it pointed to v2.1.0 build cd1a8b4 QA. Looks good

**Comment by PhotoNomad0** [comment]
@danielklapp - I reverted this change from develop branch because it caused a different problem (https://github.com/unfoldingWord/gateway-edit/issues/466).  We will have to come back to this later.

**Comment by PhotoNomad0** [comment]
Note to devs:
- this PR caused problems with persisting login due to:
  - removed server resistance - so on startup it was always starting up with default settings and then switching based on url.
  - it was switching server without restarting GWE from the beginning, so credential check was not being restarted.

**Comment by danielklapp** [comment]
> @danielklapp - I reverted this change from develop branch because it caused a different problem (#466). We will have to come back to this later.

@PhotoNomad0 Thanks for letting me know. I didn’t catch that because I was clearing out my cache every time before I tested with a different link.

**Comment by mandolyte** [comment]
Just a quick comment... it seemed to me that persistence of the server value is the root cause of the problem for which this PR was trying to address, namely to avoid accidentally using production when we shouldn't. So my idea was to trade persistence for defaults.

Maybe you guys can find a better way!

**Comment by PhotoNomad0** [comment]
> Just a quick comment... it seemed to me that persistence of the server value is the root cause of the problem for which this PR was trying to address, namely to avoid accidentally using production when we shouldn't. So my idea was to trade persistence for defaults.
> 
> Maybe you guys can find a better way!

a couple thoughts:
- it seems a key element here is the assumption that GWE should behave the same way as TCC, that specific builds should be hard-coded to specific servers.
- also there is value in being able to switch to other servers while testing - the QA server is slower, so there is benefit in testing release builds with QA server.
- perhaps keeping the server persistence can be a path forward:
  - on startup if there is no persisted server, when using a development URL, and if no server is specified.  Then we switch to QA (involves persisting the QA server and restarting the app).  That way it will have the default behavior of using QA on deploy and develop builds.  And on every subsequent startup it will start up with the QA server with no restarts needed.
  - also when URL has `?server=` we could reset the persisted server to the default for the URL, and only restart GWE if necessary.

**Comment by PhotoNomad0** [comment]
@birchamp @Joel-C-Johnson Think I have found a better approach that involves tweaking a build script to pass up netlify environment variable of CONTEXT.  At startup we can then detect if it is set to `production` or not.  Do not have to look at the url at all.

**Comment by Joel-C-Johnson** [comment]
fixed the issue - https://github.com/unfoldingWord/gateway-edit/pull/503

**Comment by elsylambert** [comment]
@PhotoNomad0 How can we test this issue?

**Comment by Joel-C-Johnson** [comment]
1. open gateway-edit website - https://gateway-edit.netlify.app/
2. Open the inspect window
3. Go to Storage-> local storage -> Click on "https://gateway-edit.netlify.app/"
4. check for the key "server" 
5. you can see the default value will be `server:""https://qa.door43.org""`

![image](https://github.com/unfoldingWord/gateway-edit/assets/25791348/05db2f66-f561-4391-9daf-0010c8efb60f)

7. change the URL to https://gateway-edit.netlify.app/?server=PROD
8. follow steps 2,3,4
9. you can see the value is changed to  `server:""https://git.door43.org""`

![image](https://github.com/unfoldingWord/gateway-edit/assets/25791348/4e1c2baf-69ef-4cdd-8d3e-1d59a800eaeb)

**Comment by elsylambert** [comment]
Looks good in v2.1.0 build 66dd56e.

**Comment by danielklapp** [comment]
Looks good to me. Tested with v2.1.0 build 66dd56e QA and also v2.1.0 build 66dd56e.
