### ISSUE TITLE
Crashes when opening old tsv format

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#439]
to reproduce open test-org/ru book of rut or 3jn

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp Issue is now fixed in GWE v2.0.0 build 14ef565

**Comment by elsylambert** [comment]
Not seeing a crash when opening test-org/ru/ruth or 3 jn. in v2.0.0 build c8df80d QA at https://release-v2-0-0--gateway-edit.netlify.app/

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp In latest build, support for the old TSV format is restored.
