### ISSUE TITLE
Editted text is not cleared when user navigates to new verse

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#440]
When user edits text, and then navigate to next verse. when you edit you see edited text from old verse.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp Issue is now fixed in GWE v2.0.0 build 14ef565

**Comment by danielklapp** [comment]
Agree that I don’t see edited text from old verse transferring to next verse. Working properly in v2.0.0 build e8a3884 QA.
