### ISSUE TITLE
When alternating back and forth between editing a verse and changing alignments, sometimes displayed text does not show latest edit

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#444]
When alternating back and forth between editing a verse and changing alignments, sometimes displayed text does not show latest edited text when you click off the verse edit box

Notes:
- seeing this problem in GWE v2.0.0 build c8df80d QA
- I am seeing this issue:
  -  in Chrome v113 on MacOS
  - in Firefox on MacOS
  - in Firefox on WIndows 10

**Comment by PhotoNomad0** [comment]
@elsylambert It looks like the problem was cause by corrupted upload data in my en_tn branch.  Looking into the cause.

**Comment by danielklapp** [comment]
Seems to be working properly in v2.0.0 build 1973adb QA.
