### ISSUE TITLE
Unable to Save tNotes

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#446]
Edits are not saved and seeing 422 error on console.
![Screenshot 2023-05-18 at 11.11.46 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/cc2de04d-2671-4285-98c4-29d27f7c304e)

**Comment by PhotoNomad0** [comment]
@elsylambert I also notice that the data is truncated in your user branch (see https://qa.door43.org/unfoldingWord/en_tn/commit/c61efc3a24e5a2028a4b74ba0162312ee573128b).  I'm seeing the same thing on save.  It's like it is only saving two checks.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This is fixed in v2.0.0 build 1973adb

**Comment by danielklapp** [comment]
After making edits to translationNotes user is able to save. Not seeing an error code in the console. Seems to be working properly with v2.0.0 build 1973adb QA.

**Comment by elsylambert** [comment]
Not seeing the problem in v2.0.0 build 1973adb QA. Able to save edits in tNs.
