### ISSUE TITLE
Word Aligner does not show broken alignment with unaligned original language words

### ISSUE THREAD

**Issue by jincypjose** [unfoldingWord/gateway-edit#448]
![Screenshot from 2023-05-23 21-14-30.png](https://images.zenhubusercontent.com/5f8fb2e83cdc9276e3df86d3/a6792dc5-1c84-4110-b7b3-f5f950336650)

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This is fixed in v2.0.0 build 1973adb

**Comment by danielklapp** [comment]
Not seeing this issue in v2.0.0 build 1973adb QA. The broken icon seems to be working properly.

**Comment by elsylambert** [comment]
Looks good in v2.0.0 build 1973adb QA. Broken link icon works properly.
