### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#450]
- Release Steps:
  - [x] update language.json - should we automate?
  - [x]  configure netlify to auto-build release branch `release-v2.0.0` (add as additional branch to Deploy contexts under https://app.netlify.com/sites/gateway-edit/settings/deploys)
  - [x]  create release branch `release-v2.0.0`
  - [x]  Ping QA that release branch is ready for testing (https://release-v2.0.0--gateway-edit.netlify.app/)

- When QA has OK'd release branch, make final release by merging to main:
  - [x] Create PR from `release-v2.0.0` branch to main branch.
  - [x] Merge pull request `release-v2.0.0` branch to main . Record new build version for v2.0.0 here: v2.0.0 build daf88b
  - [x] Ping QA that release is live at https://gatewayedit.com/ - inform them that current build to verify is now version recorded above ^^^
  - [x] Final Go ahead for publish from QA
  - [x] Create a tag
  - [x] Publish release notes.
  - [x] Add release notes to the draft release and publish on github.
  - [ ] Announce on forum.door43.org

- Merge release-v2.0.0 back into develop branch:
  - [x] create PR to merge single-scripture-rcl release-v2.0.0 branch into master
  - [x] create PR to merge translation-helps-rcl release-v2.0.0 branch into master
  - [x] create PR to merge resource-workspace-rcl release-v2.0.0 branch into master
  - [x] create PR to merge GWE release-v2.0.0 branch into develop
  - [x] review and merge the above PRs

**Comment by elsylambert** [comment]
v2.0.0 build daf88be is released and is available at https://gateway-edit.netlify.app/
