### ISSUE TITLE
Upgrade bible-reference-rcl to React 18

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#452]
This issue is to cover work with Rolf's PR that upgraded bible-reference-rcl to be compatible with React 18, and the work we did to upgrade the unit tests to use a React 18 compatible library (React testing library).

**Comment by birchamp** [comment]
This includes adding the unit tests

**Comment by PhotoNomad0** [comment]
@Birch - The latest bible-reference-rcl is at 1.2.0 and has the updates from SIL to React 18. 

Note that GWE will also need updates to the CSS to accommodate the wider reference fields.
