### ISSUE TITLE
Close merge dialog on resource reload

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#456]
Right now mergeToMaster state updates on saves and loads. Instead, it would be ideal to check mergeToMaster state every time card content is actually changed (this will happen on save and whenever we decide to merge to master).

DoD:

- [ ] Merge status correctly updates on a card load
- [ ] When committing a merge, merge dialog only closes after needed cards reload resources

**Comment by danielklapp** [comment]
Merge status correctly updates and merge dialog closes after the needed cards reload. Tested with v2.1.0 build b8e0a95 QA. Looks good
