### ISSUE TITLE
BUG: Multiple branches/PRs created on editing card

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#458]
When editing a card that does not have a user branch, it sometimes creates two user branches. 
This is what is causing issues with the dcs-branch-merger component, as a user branch will not always be deleted when there are multiple user branches.

DoD: 
- [ ] Only one user branch is created when a card is edited

**Comment by danielklapp** [comment]
Looks good, saw one user branch created when making an edit to a card. Tested with v2.1.0 build b8e0a95 QA.

**Comment by elsylambert** [comment]
Not seeing this issue in v2.1.0 build 66dd56e QA. Only one user branch is created per resource when edits are made.

**Comment by danielklapp** [comment]
Also looks good to me in v2.1.0 build 66dd56e QA.
