### ISSUE TITLE
BUG: Scripture resources are not reloading correctly on merge

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#459]
When clicking on merge to master, the changes that the user just merged to DCS are not displaying in the scripture cards.

DoD: 
- [ ] When user saves changes and merges them to master, those changes should be displayed in the scripture card
- [ ] The scripture card content should be coming from the master branch, not a user branch

**Comment by danielklapp** [comment]
Changes are displayed in the scripture card and the content is coming from the master branch. Tested with v2.1.0 build b8e0a95 QA. Looks good
