### ISSUE TITLE
Bug: loadGlBible() in translation helps is loading bibles from Door43-Catalog - should be reading from current org

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#460]
Bug: translation-helps-rcl is loading GL bibles from Door43-Catalog - should be reading from current org/owner.   The GL bibles are used for looking up GL quotes. This will be more important for languages other than English.

**TODO:**
- loadGlBible() is hard coded to DOOR43_CATALOG - should add owner as parameter to function and use that in resourceLink.
- also getGlAlignmentBiblesList() is hard coded, but should use the owner passed.

**Comment by birchamp** [comment]
@theNerd247 in Zenhub you can move issues from sprint backlog to in progress to in review (ping whoever you want to do the review).   If you grab an issue to the left of the Sprint Backlog pipeline please talk to me about it first. Essentially the left side of the board is mine and the Sprint Backlog and right side is the devs. The handoff typically occurs at Sprint Planning

**Comment by theNerd247** [comment]
@elsylambert has this issue gone through QA yet?

**Comment by birchamp** [comment]
If you look in https://app.zenhub.com/workspaces/gatewayedit-5fa302df5c4ec9001f1d5d54/board you'll see it still in the QA pipeline, not QA done.

**Comment by theNerd247** [comment]
Thanks! I just haven't heard any feedback for a while so I wasn't sure if it's status was accurate (it hadn't been moved from in QA to something else).

**Comment by birchamp** [comment]
Good point. It might have gotten missed.

**Comment by elsylambert** [comment]
@theNerd247 I looked at this issue this afternoon but I need some help testing this issue. Can you please add the steps to test this issue?

**Comment by theNerd247** [comment]
Sure! see #495 for the testing process

**Comment by elsylambert** [comment]
Verified in v2.1.0 build 66dd56e QA. TWL card is loading data from the user branch/current org instead of Door43 catalog. Looks good.

**Comment by danielklapp** [comment]
Agreed that content is loading into cards from user branch/current org. Tested with v2.1.0 build 66dd56e QA.
