### ISSUE TITLE
Save failing after broken alignment is fixed

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#464]
1. Open gE, edit a scripture and save.
2. Note that Broken alignment link is activated, Click on the icon to open the alignment window.
3. Complete the alignment and click on Accept.
4. Note that Save button is enabled, click on Save.
5. Fails with error on console
![Screenshot 2023-06-06 at 9.45.32 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/28dabed0-6e34-47d2-af65-784f533f9342)

**Comment by danielklapp** [comment]
Looks good, not seeing any errors after saving in console. Tested with v2.0.0 build 87aa21b QA.

**Comment by elsylambert** [comment]
Not seeing the problem in v2.0.0 build 87aa21b QA. Save is working fine after the edits and alignments for large books.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp - Added error message for when branch fails to create. Latest fix is in v2.0.0 build 954c4d3

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp - Added error message for when branch fails to create in a resource card. Latest fix is in v2.0.0 build 78fc9be

**Comment by elsylambert** [comment]
@PhotoNomad0 Seeing this Network error when trying to save with a custom test slower connection.
![Screenshot 2023-06-15 at 9.15.11 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ddbe51f5-dc64-441b-886a-e178c63698b7)

**Comment by elsylambert** [comment]
Passing this issue in v2.0.0 build 78fc9be QA. I see the network error the first time user branch is created with slower connections but then afterwards it works fine. Able to edit and save scripture edits and alignments without error.
