### ISSUE TITLE
Delete rows from TSV7(TN,TWLs)

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#484]
- click minus to delete a row
- Popup confirmation like it shows in tCC
![CleanShot 2023-07-27 at 14.38.14.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/df0d58ba-ff31-4729-9b50-649198952f3a)![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/2c206c2c-5ace-4bc3-abca-bd4675a975cc)

For table view:
![CleanShot 2023-07-27 at 14.35.01.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/3d60da08-4bfc-42c3-8cbb-6349678b5f9d)

**Comment by elsylambert** [comment]
For tWLs, the add/delete buttons must be for each row, since the card displays the list of words.

**Comment by birchamp** [comment]
@jincypjose @theNerd247 @kintsoogi Here are some various screenshots of different UIs for adding and removing rows.  The first one (material-ui) is what I was trying to describe yesterday.  After that are just a few of the seemingly infinite ways people have done it. What's your pick?
1. https://mui.com/material-ui/react-table/
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/70ddd359-fab7-4756-924d-ed12ed4f686d)
2. https://material-table.com/#/docs/features/actions
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/aecdf122-7f98-41ac-adbc-03232235dd70)
3. https://github.com/RXNT/react-json-schema-form-extras/issues/98
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/e85a4661-323d-4675-8e84-c240218d7a55)
4. https://stackoverflow.com/questions/51095527/delete-dynamically-added-table-row-react-js
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/0564b2c2-8ee0-4332-bd37-3186024b6638)
5. https://www.youtube.com/watch?v=MINQoCSBmds
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/175232be-9b40-46e7-999d-68fac4847f8a)

**Comment by theNerd247** [comment]
I really like (2). The icons are self explanatory and as someone who reads left to right it flows well.

**Comment by theNerd247** [comment]
(1) is great if the number of actions per row is >= 3 (as the icons would take up to much real-estate)

**Comment by jincypjose** [comment]
I too liked 1 and 2 both makes sense.

**Comment by birchamp** [comment]
We will do #3 and put both add and delete button in an actions column

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This issue is in the latest GWE develop build v2.1.0 build f85dc07

**Comment by elsylambert** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmIyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8df37e52699a799e795162cae039fc084494669/Screenshot%202023-11-21%20at%2011.21.34%E2%80%AFAM.png)

**Comment by danielklapp** [comment]
Verified everything listed on the test instructions. Looks good to me and tested with v2.1.0 build f85dc07 QA.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp I was able to reproduce the problem I saw before:  

https://github.com/unfoldingWord/gateway-edit/assets/14238574/f34ccc91-df8f-442c-a0f1-e889ffd0af2f

**Comment by PhotoNomad0** [comment]
@kintsoogi - It seems related to adding the tN to the end of the book.  It's throwing an exception.

<img width="583" alt="Screenshot 2023-11-22 at 7 30 43 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/7ef0ab57-5170-4fac-8347-e26bcc3b2dca">

**Comment by elsylambert** [comment]
Moved the bug to #592
