### ISSUE TITLE
Need For Meta-Repo/Workflow Discussion Placeholder

### ISSUE THREAD

**Issue by theNerd247** [unfoldingWord/gateway-edit#498]
Consider the following issues:

- [Library Issues / Repository Organization](https://github.com/unfoldingWord/uW-Tools-Collab/issues/7)
- [Multi-Repo PR Process Needs Improvement]()

These discussions (and their likeness) tend to not fit neatly into a single repository. 
Issues need to belong to some project board
project boards need to belong to a repository

The current solutions are two fold:
1. place such discussions as issues into a repository that currently gets a lot of attention (such as `gateway-edit`). This approach is great for issue-like features however initial notification / discovery can be problematic.
2. create a Discord thread and mention the appropriate people. This approach is great for initial visibility however issue-like features don't exist and threads can easily get forgotten about.

As unfoldingWord moves more towards an OCE / library development philosophy I see a need for a place to manage non-repository / multi-repository issues.

Below are a few initial thoughts regarding some solutions:

1. Create issues in their "closest" repository and use Discord as a means to initiate discovery/discussion on that issue.
2. Use an organization wide [github project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects)

**Comment by theNerd247** [comment]
@birchamp @elsylambert

**Comment by birchamp** [comment]
@theNerd247  I just created [the repo](https://github.com/unfoldingWord/uW-Tools-Collab)  for this.
