### ISSUE TITLE
Cards Sync Feedback showing ugnt and uhb under Cards With No Changes To Save

### ISSUE THREAD

**Issue by danielklapp** [unfoldingWord/gateway-edit#510]
After clicking on hamburger menu and then merge my work, Cards Sync Feedback pop up window appears.  Under Cards With No Changes To Save, the last card listed is uhb when in Old Testament or ugnt when in New Testament. It will show both ugnt and uhb listed if you switch back and forth from Old and New Testament. They probably shouldn’t be listed at all since there’s no save button on those cards. I highlighted where they are shown on pop up. 

![Screenshot 2023-07-25 at 8.35.19 AM.png](https://images.zenhubusercontent.com/63e2b3aebe65b0eb5b78a45f/8eb36ecc-5251-40d7-afba-736eb3a71e88)

**Comment by elsylambert** [comment]
Text to be changed on the card: 1. UnfoldingWord® Literal Text instead of Unfolding Word Literal Text
2. UnfoldingWord® Simplified Text instead of   Unfolding Word Simplified Text.
3. Remove ugnt and uhb from the card.

**Comment by danielklapp** [comment]
Looks good to me. Tested with v2.1.0 build d431e66 QA.

- The Update my content button has been removed from the original text. 
- Under Cards With No Changes To Save the uhb and ugnt (Original Source Text) are not listed.  
- All titles have been corrected.

**Comment by elsylambert** [comment]
Looks good in v2.1.0 build d431e66 QA

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1pEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea85ec310df3ae7430c6c0169b55c6e6e102aee0/Screenshot%202023-10-17%20at%209.06.05%E2%80%AFAM.png)
