### ISSUE TITLE
Merge Issue: UST/ULT content merged into wrong usfm(book)

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#514]
ULT/UST in Scripture pane shows wrong verses for the selected book
v2.1.0 build 66dd56e QA
Open Org:Unfoldingword lang: en

Case 1: en_ust, UST shows contents from Lamentations in Titus.
This commit made the change: https://qa.door43.org/unfoldingWord/en_ust/commit/7fef8576fcd91497f508aea4f285dfb3c2cd53a9
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblF0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--523a35ec15b6b2335d923300768093999a5c63bf/Screenshot%202023-08-23%20at%208.44.47%20AM.png)

Case 2: Open Titus 1:1, it looks fine, navigate to 1:2, note that ULT shows verses from Mathew 1:2. This breaks the alignment and the issue written up in #513![Screenshot 2023-07-28 at 8.09.43 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/0f471824-e96b-42ba-9566-12cbabd98959)

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp I am trying to reproduce this, but not seeing this on the same build.  Is there anything specific I need to do?  Is this a reduced bandwidth issue?

**Comment by danielklapp** [comment]
@elsylambert @PhotoNomad0 Here are the steps I preformed yesterday.

- Logged into gateway edit, it was in the book of Matthew and there was a red dot to update my content in UST.
- Clicked update my content in UST card not the in header, it updated. 
- Later in the day I came back to gateway edit and changed books from Matthew to Titus and started testing by writing test edit in UST, TN, and TQ.
- Then I merged my work.
- After merging I edited again by deleting test edit in UST, TN, and TQ.
- Then merged them in.

**Comment by elsylambert** [comment]
Verified in v2.1.0 build 9f43681. This issue is resolved. The scripture panes ULT/UST loads correctly after the books are switched from OT to NT, OT to OT and NT to NT. Edits are saved in correct branches without overwrite.

**Comment by elsylambert** [comment]
v2.1.0 build 34af947 QA. Not seeing data corruption while saving Scriptures when books are switched and merging is working as expected.

**Comment by danielklapp** [comment]
Not seeing books overwriting other books in ULT/UST. When making edits, switching books, or merging. Working properly in v2.1.0 build 516af56 QA.
