### ISSUE TITLE
Seeing error while creating a user branch for ULT

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#516]
https://release-v2-1-0--gateway-edit.netlify.app/
v2.1.0 build 66dd56e QA
Org:unfoldingWord, lang :en
This happens if you edit the same verse that was edited by other user branch.
Opened PHP 1:1 and edited a verse in ULT card, when clicked on Save, the app threw Network error as in the screenshot.
![Screenshot 2023-07-28 at 8.41.40 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/116fd48b-fcbb-48a7-93de-3df521e8edef)

Steps:
1. Open book CoL 1:1(e.g)(USER 1)
2. Make edits to ULT, save and merge to master.
3. login using a different user login(USER 2)
4. Open the same verse Col 1:1 there could be two scenarios :a. USER 2 has a user branch already ,so Update my content icon should get a red dot 🔴 indicating there are changes to be updated from master to user branch. Click on the icon to update the content. You see errors on the console and endless loading spinner on the ULT resource card written up in #517.
b. USER 2 gets a new user branch and thus the changes from step 2. would be seen.
5. Edit the verse with new edits and click on save. Note that it throws network error.

![Screenshot 2023-08-02 at 9.04.14 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/845c2db5-e6ec-470a-a8a9-a286525a3e17)

**Comment by danielklapp** [comment]
Agree with the process listed above does work. Not seeing network error while creating a user branch for ULT. Tested with v2.1.0 build 9f43681 QA.
