### ISSUE TITLE
Update my content on ULT/UST is throwing errors on console

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#517]
https://release-v2-1-0--gateway-edit.netlify.app/
v2.1.0 build 66dd56e QA
When Update my content icon had a red dot indicating that an update is available for ULT, I clicked on the icon to update and got endless Loading Resource message with errors on the console.
![Screenshot 2023-07-28 at 9.11.28 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/596754e2-43c7-44e1-b94e-0fb8ee6078ca)

**Comment by elsylambert** [comment]
![Screenshot 2023-07-28 at 10.58.02 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/696979a5-4783-4df6-89ca-543947a823b9)

**Comment by elsylambert** [comment]
After deleting all the old branches, no longer seeing this problem in tQ in v2.1.0 build 66dd56e QA.

**Comment by danielklapp** [comment]
Starting with a fresh branch, not seeing errors in console. Tested with v2.1.0 build 66dd56e QA.

**Comment by elsylambert** [comment]
This morning testing on en_ust Galatians and seeing errors again. My user branch was created yesterday auto-ElsyLambert-GAL and this morning when I logged in I saw a 🔴 red dot to update my content. When I clicked on the icon, I am seeing errors:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUkwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--33577d2a3c33aeb457ce93d2062b456089e8596e/Screenshot%202023-08-24%20at%208.45.29%20AM.png)

**Comment by danielklapp** [comment]
When user clicks Update my content, not seeing errors in console or the endless Loading Resource message. Tested with v2.1.0 build 7b1667f QA.
