### ISSUE TITLE
Merge my work shows the checklist back again after Resources are merged

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#518]
Steps:
- Open gE, testing with org:unfoldingWord, en.
- Open a book (e.g TIT) that has unmerged, saved edits.
- Go to Menu, note that Merge my work has a red dot indicating that there are changes that can be merged to master.
- Click on Merge my work and choose the resources to merge, add notes and merge. Note that the checklist Resources disappear as merge happens for the chosen resource  and soon after the resource appears again in the list unchecked, this is confusing to the user,
- ![Screenshot 2023-07-31 at 9.28.38 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ff3ba955-f533-4e5f-8367-afca5ae6e96f)
- DCS shows that the user branch was merged.
 ![Screenshot 2023-07-31 at 9.29.27 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/47d1f980-bead-416c-9953-d8112b0fedc0)

**Comment by elsylambert** [comment]
@kintsoogi No it did not show any merge conflict message or error. After it popped back in ^^ as in the snapshot, I tried to check them back and merged again, then it showed errors on the console.![Screenshot 2023-07-31 at 9.31.37 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/1e229d4e-2cc4-49ac-8e4f-82cbdb79632c)

**Comment by jincypjose** [comment]
Not able to replicate the issue
@kintsoogi  that make sense. Shall we ask birch too?

**Comment by elsylambert** [comment]
@kintsoogi @jincypjose If it helps in anyway, this is my user branch for tN https://qa.door43.org/unfoldingWord/en_tn/src/branch/ElsyLambert-tc-create-1
and tQ: https://qa.door43.org/unfoldingWord/en_tq/src/branch/ElsyLambert-tc-create-1
UST: https://qa.door43.org/unfoldingWord/en_ust/src/branch/auto-ElsyLambert-TIT

Maybe, your user branches did not have previous changes. When I started testing merge, I was constantly making edits to Resources, saving and merging them. Sometime saved the changes and merged them together. So my user branch had changes constantly. 
Also the Scripture Resources like ULT and UST are merging changes per Book branch while tN and tQ are checking conflicts and merging on all the files in the tN/TQ repo. So even if I have cards open in TITUS but if I had previous changes saved but not merged in Mathew for tN or tQ, when I merge my work, it checks conflict/merges the changes from Mathew(Uesr may or maynot be aware of this) @birchamp

**Comment by elsylambert** [comment]
After deleting all the old branches, no longer seeing this problem in v2.1.0 build 66dd56e QA.

**Comment by danielklapp** [comment]
Starting with a fresh branch, not seeing any problems with checklist showing back up after merging resources. Tested with v2.1.0 build 66dd56e QA.
