### ISSUE TITLE
Alignment is broken for the whole verse after a second edit is made to UST in a new user branch

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#520]
- Delete any previous user branch.
- Login to gE and make edits to UST or ULT, Note that the alignment link shown Broken chainlink.
- Save the edits. Check the Broken chainlink, it shows the only new edits left in the word bank.
- After the Save in the above step, make some more edits to the same verse.
- Click on the broken chainlink, note that all the aligned words are moved back to the word bank.
- 
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/be17f703-b0d8-4f2d-86d6-cdc808f0e7d9)

**Comment by elsylambert** [comment]
Retest after #514 is fixed.

**Comment by PhotoNomad0** [comment]
@elsylambert Testing with latest 2.1 release.  Only seeing the words I added in the word bank.
<img width="1389" alt="Screenshot 2023-09-11 at 8 50 08 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/967db34a-5d87-4460-ba69-451d087b261c">


You didn't mention saving the edit in the step - I'll give that a try now.

**Comment by elsylambert** [comment]
v2.1.0 build 34af947 QA. Not seeing the alignment broken but after I edit UST for the first time and save it as a new branch, seeing Project Manifest failed to Load message.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEtLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fccad4860936c570197d2f3184e6fb6bb50b21d2/Screenshot%202023-09-11%20at%2010.50.21%20AM.png)
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFNLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--175ea31cd40b1ac5cb4e89a49eb0aa29a865bee4/Screenshot%202023-09-11%20at%2010.50.04%20AM.png)

**Comment by PhotoNomad0** [comment]
@elsylambert Having trouble reproducing this.  I know I saw it when QA was having problems.  So I suspect it is a timing issue.  Will keep trying.

**Comment by elsylambert** [comment]
@PhotoNomad0 wrote it separately in https://app.zenhub.com/workspaces/gatewayedit-5fa302df5c4ec9001f1d5d54/issues/gh/unfoldingword/gateway-edit/539

**Comment by elsylambert** [comment]
Moving this issue to QA watchlist.

**Comment by danielklapp** [comment]
Testing in v2.1.0 build 7b1667f QA 
Like steps above ^^^  here’s my saved console log when replicating it.
[release-v2-1-0--gateway-edit.netlify.app-1695093583686.log](https://github.com/unfoldingWord/gateway-edit/files/12664124/release-v2-1-0--gateway-edit.netlify.app-1695093583686.log)

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp Fix is in v2.1.0 build fc21e59

**Comment by danielklapp** [comment]
Looks good to me. Not seeing this issue of the alignment breaking the whole verse after a second occurrence of a word to ULT / UST. Tested with v2.1.0 build fc21e59 QA.
<img width="1435" alt="Screenshot 2023-09-20 at 2 35 21 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/d7d12ce5-d670-42ee-9d3b-3dceb23b3aae">

<img width="1435" alt="Screenshot 2023-09-20 at 5 13 28 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/5dd5c0a0-74ce-4654-8be8-3fd7b6d9bbe1">

**Comment by elsylambert** [comment]
Not seeing alignment breaking for the whole verse when there are multiple occurrences of a word or on multiple edits and saves. Looks good in v2.1.0 build fc21e59 QA.
