### ISSUE TITLE
Hotkeys for selecting words for aligning scripture using Shift Click

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#524]
Scenario : Users want to select words from the Word Bank using Shift  + Click.
when they shift click on two words in the word bank list, all the words in between those two words should get selected.
then all the selected words can be dragged into the alignment area  together.

DOD:
Users should be able to click on the first word to select and then shift-click on a second word to select it. All the words between the two words should be selected as well.

**Comment by jincypjose** [comment]
The idea behind it will be
identify the shift click
when shift + click on an item --> get the index of the item from the words list
when shift + click on second item ---> get the index of it
then get all item in between the indexes including start and end
the remaining is drag and drop (In existing code )

**Comment by jincypjose** [comment]
Some of the document i think need to be reffered
https://react-hotkeys-hook.vercel.app/docs/intro
https://devtrium.com/posts/how-keyboard-shortcut
https://medium.com/cogito-engineering/keyboard-shortcuts-in-react-and-how-they-help-the-annotation-team-14d22fd36c4a
https://www.npmjs.com/package/react-hot-keys

**Comment by PhotoNomad0** [comment]
@elsylambert - For the DOD - It seems that the desired workflow is to click on the first word to select and then shift-click on a second word to select it and all the words between the two words.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp - This is now in GWE v2.1.0 build f845565

**Comment by elsylambert** [comment]
Looks good in v2.1.0 build f845565 QA. Shift+ click selects all words between two selected words.

**Comment by danielklapp** [comment]
Agree that clicking a word at the top of the list and then Shift+clicking another word below it, the words between them get selected as well. Looks good to me. Tested with v2.1.0 build f845565 QA.
