### ISSUE TITLE
Update content shows conflict in en_tn when edits are made in a different book

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#528]
Update content shows conflict in en_tn when edits are made in a different book.
Steps:
1. Open tCC>en_tn>edit a file(e.g Mathew)
2. Save the edits and logout.
3. Open GE> navigate to Titus> on TN card. note that Update my content icon has a 🔴 red dot. Click on it and it will show Conflict error. 
4. Go to hamburger menu>Merge to master>select tN. The merge happens and the Update my content icon 🔴 red dot is gone.

Conflict Error should not show for a different book.

**Comment by elsylambert** [comment]
Verified in v2.1.0 build 34af947 QA. Edits made to en_tn are not showing conflicts when they are made in different books. When edits are made to same book and same note, the red dot is indicated and conflict error is shown, which is the expected behaviour. Looks good.

**Comment by danielklapp** [comment]
Agree when editing two different books in en_tn, conflicts aren’t shown.  Working properly in v2.1.0 build 10ae431 QA.
