### ISSUE TITLE
Change the 'Scripture' in the title to the Name of the scripture

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#53]
Instead of having the word "Scripture" at top of the scripture cards, the Name of the scripture resource should be the title of the card. 

**Current:**
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/482341d7-6cf5-4ac1-ac25-ff88feb8c82b)

**New:**
![Zulip - unfoldingword 2021-01-27 09-23-43.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/94490729-7de9-4a87-8eb3-0ca9fbfe347c)

**Comment by cckozie** [comment]
Looks good in v0.2.0 build cbad9c9

**Comment by elsylambert** [comment]
Looks good in v0.9.0 build ab13659. Seeing the title instead of the word "scripture".
