### ISSUE TITLE
Copying Original Quote from the scripture pane 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#534]
In GatewayEdit Scripture pane, it is very difficult to select multiple Original language word using a mouse for copying and pasting in Original Quote field in tN card.

Users should be able to select text the way they would with any text. The lexical data should not show until the user clicks the original language word (the same way that tC handles this). 

DoD:
---
Users can select original language text the same way they would in any text box. Users can click the original text lexeme to see the lexical data.

**Comment by elsylambert** [comment]
Looks good in v2.3.0 build bd4a646 QA. Users are now able to copy text from the scripture pane.

**Comment by danielklapp** [comment]
I agree that user can copy the Original language text from scripture card and paste it in tN card. Tested with v2.3.0 build bd4a646 QA.
