### ISSUE TITLE
Highlighting breaks when Occurrence number is changed

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#535]
Highlighting breaks when Occurrence number is changed on tN card for multiple occurrences of a word.  

Updating to the latest scripture-resources-rcl is the first step to fixing this, but some changes may be necessary in the single-scripture-rcl.

DoD:
---
Highlighting multiple occurrences works the same as tC based on the occurrence number.  

Details:
---
Highlighting should follow the logic outlined on the D43 forum:
https://forum.door43.org/t/parascriptural-tab-separated-value-format-specification-v2/870
* `Occurrence` (integer string) – used in all resources to qualify the `OrigWords` or `Quote` fields
* Note that word matches are defined to be WHOLE WORD matches – simple string searches will fail as they might find (English example) “one” in “undone” – the `Occurrence` indicates the occurrence of the entire word including accents and cantillation marks and any punctuation that’s included
* Note that the pieces on either side of Hebrew maqaf “־” can be specified as stand-alone words, i.e., maqaf should also be considered a word divider
* `-1` : entry applies to **every occurrence** of OrigWords/Quote in the verse (cannot be used with ampersand discontiguity divider in OrigWords/Quote)
* `0` : (not used in TWL) entry **does not occur** in Quote (for example, “Connecting Statement:”)
* `1` : entry applies to **first** occurrence of OrigWords/Quote only
* `2` : entry applies to **second** occurrence of OrigWords/Quote only, etc.
*

**Comment by birchamp** [comment]
@PhotoNomad0 @kintsoogi @abelpz I thought we had done a highlighting library that could be used in multiple apps. Is that being used here?

**Comment by abelpz** [comment]
@birchamp looks like gateway-edit is not using the latest version of scripture-resources-rcl which handles highlighting.

**Comment by birchamp** [comment]
@elsylambert please test this same issue in tCC.

**Comment by elsylambert** [comment]
v2.2.0 build 3179311 QA. Highlights work fine in scripture resources when Occurrence number is changed in tNotes.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEV1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5106648f7d6c03bbdaa55a39dc40e9e2124d4a0e/Screenshot%202023-12-04%20at%205.13.33%E2%80%AFPM.png" alt="Screenshot 2023-12-04 at 5.13.33 PM.png" />
