### ISSUE TITLE
First time edits shows Project Manifest not loading on the card for UST

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#539]
v2.1.0 build 34af947 QA. Not seeing the alignment broken but after I edit UST for the first time and save it as a new branch, seeing Project Manifest failed to Load message.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEtLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fccad4860936c570197d2f3184e6fb6bb50b21d2/Screenshot%202023-09-11%20at%2010.50.21%20AM.png)
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFNLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--175ea31cd40b1ac5cb4e89a49eb0aa29a865bee4/Screenshot%202023-09-11%20at%2010.50.04%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHVLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7fce3916f668c67eaae78f7efe327894698a00ed/Screenshot%202023-09-11%20at%204.25.39%20PM.png)
@PhotoNomad0 

Also reference notes on: https://github.com/unfoldingWord/gateway-edit/issues/520

**Comment by PhotoNomad0** [comment]
@elsylambert The fix is in 2.1.0 build 62a5ffe

**Comment by elsylambert** [comment]
Looks good in v2.1.0 build 62a5ffe QA. Not seeing Manifest fail to load when a book is edited in UST.

**Comment by danielklapp** [comment]
Agree, not seeing manifest fail to load after editing and saving in UST. Working properly in v2.1.0 build 62a5ffe QA.
