### ISSUE TITLE
Update Content on TSV Add Without Having to Save

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#543]

**Comment by danielklapp** [comment]
Getting a 404 or 401 errors after clicking the add button in the Add Row pop-up. Testing with v2.1.0 build 5e71fc7 QA. 

Steps to recreate errors 
- Add a row to any tN, twl, or TQ. Make edits to Add Row pop-up and click add button. After clicking add button you receive the 401 error (Error creating edit branch en_twl).
<img width="1440" alt="Screenshot 2023-11-14 at 11 03 59 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/fb299f53-2d93-499a-8a18-2013648b7fce">

- If you click send feedback you get 404 error page or
<img width="1440" alt="Screenshot 2023-11-14 at 11 04 18 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/33a8a055-12c3-4a53-b8e4-fba4810e1c55">

- if you click cancel it takes you back to page, you get an endless loading on Update my content and an invalid token error after clicking Update my content on card.    
 
<img width="1440" alt="Screenshot 2023-11-14 at 11 05 39 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/0f8b4295-d223-4114-afdb-e7cc8cb1f0c1">

**Comment by elsylambert** [comment]
Saving new note in tN: 
New note is saved without having to click save button and positioned itself next to the parent note.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG5aQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--106c6d1699a4051240c5e0220148b4f62d87ddb9/Screenshot%202023-11-15%20at%209.33.17%E2%80%AFAM.png)
