### ISSUE TITLE
Add TSV to Next Index and Navigate There

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#544]

**Comment by elsylambert** [comment]
- [ ] Navigate to front matter and make sure that app does not crash (should have no TSVs)
- [ ] Add a row to either tN, twl, or TQ. Make sure resource added is in the same verse
  - [ ] Verify that the added TSV exists within the resource
    - [ ] Verify that you are now navigated to the newly created row

**Comment by danielklapp** [comment]
Tested with v2.1.0 build 65fd995 QA.

- [ ]  Navigate to front matter and make sure that app does not crash (should have no TSVs)
- [ ]  Add a row to either tN, twl, or TQ. Make sure resource added is in the same verse
- [ ]  Verify that the added TSV exists within the resource
- [ ]  Verify that you are now navigated to the newly created row
