### ISSUE TITLE
Reference Range Capability for Add TWL

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#545]
The user should be able to edit the reference field during the add process to any allowable reference - both single references and reference ranges

DoD
---
Adding a row with a reference range functions as a single reference does.

**Comment by birchamp** [comment]
Seems to be working in TN

**Comment by danielklapp** [comment]
Scripture card shows both types of reference ranges. When navigating to either reference, the tsv item is there. Tested with v2.3.0 build bd4a646 QA

<img width="1439" alt="Screenshot 2023-12-20 at 12 40 52 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/26216d94-64f6-4bea-8b95-378b6de1c810">

<img width="1439" alt="Screenshot 2023-12-20 at 12 41 58 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/1d9d17ec-b0d2-4d8b-8805-112055fc6b28">
