### ISSUE TITLE
Update my content does not refresh the card data

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#546]
When there is a new content to load, and user clicks on Update my content icon button, the spinner spins and looks like content is updated to latest but the cards do not show the changes until the page is refreshed.
Steps:
- Login as User 1 and edit UST/ULT for any book say Mathew 1:1. add some new text and save. (This step is to create a USER branch for user 1). Logout.
- Login as  User 2 and edit Mathew 1:2 in ULT/UST and some text and save. From Menu>Merge my Work. Choose UST/ULT and submitt. This should merge the changes in step 2 into master and User 2 branches should get deleted.
- Login as User 1 again and navigate to Mathew 1: 2, you should see red dot over the Update my Content icon, click on it.
- The spinner spins but the latest content is not loaded.
- Refresh the page and you should be able to see the latest content.

**Comment by danielklapp** [comment]
Looks good to me. When user clicks on Update my content button, the content on the card updates without having to refresh the page. Tested with v2.1.0 build d431e66 QA.

**Comment by elsylambert** [comment]
Not seeing this problem in https://develop--gateway-edit.netlify.app/ with v2.1.0 build d431e66 QA. Cards are updated correctly with the latest content from master.
