### ISSUE TITLE
Need to add support for aligning chapter headers/front matter to GWE

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#559]
Need to add support for aligning chapter headers/front matter to tCore. This is especially needed for Psalms alignment.

In Psalms there is chapter headers/front matter that is in the original language that needs to be aligned.

Not sure if any other book have this need.

This is directly related to https://github.com/unfoldingWord/translationCore/issues/7536

DoD
---
Users can align scripture text under the \d marker.

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert  A few options here in handling error conditions when user clicks align:
1. we can add separate warning dialogs:
  - There are no align-able words in the target language
  - There are no align-able words in the original language
2. we can add single warning dialog for when either target language or original language does not have align-able words

It would probably be less confusing to do option 1 (my recommendation).

And what message should we show on the error?

**Comment by elsylambert** [comment]
I would suggest option 1. 

Case I: When the Scripture text do not have words to align, the message could be "There are no words to align in the Literal/Simplified Scripture Text"
Case II: When Original language does not have words to align, the message could be "There are no words to align in the Original language"

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert  It was suggested that when navigating by chapter or book that we default to verse 1 and not front.

**Comment by PhotoNomad0** [comment]
@elsylambert Merged the code into develop branch, but seeing a strange runtime bug when it shows an alignment error and use clicks cancel.  Looking into it: 
<img width="2011" alt="Screenshot 2023-11-01 at 1 20 52 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/f7e941d4-e094-4383-84f5-ab8c72a62911">

**Comment by PhotoNomad0** [comment]
@danielklapp ^^^

**Comment by PhotoNomad0** [comment]
I was able to reproduce this in a debug build of the develop branch.  I see a clue as to what is going on:
<img width="1728" alt="Screenshot 2023-11-01 at 3 38 18 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/aa8d0621-be87-40d5-9007-cf284d7adf66">

**Comment by PhotoNomad0** [comment]
@kintsoogi I was able to narrow this down to being a crash in 'ta' resources.

**Comment by PhotoNomad0** [comment]
@elsylambert - This should be working in latest develop build

**Comment by elsylambert** [comment]
Front matter support looks good in v2.1.0 build f845565 QA. By default the navigation is done to verse 1, but verse dropdown as Front option in the top. It enables users to align front matter.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9aQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f00a9f1e25e94b3fc3ed0b13fd5e6ce32823869/Screenshot%202023-11-15%20at%2011.11.55%E2%80%AFAM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0RaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5194d571a884a077bab22e2b8bc675754fbf77f8/Screenshot%202023-11-15%20at%2011.09.16%E2%80%AFAM.png)

**Comment by elsylambert** [comment]
@PhotoNomad0 I wrote highlighting issue separately in #579. Highlighting is not working for front matter.
