### ISSUE TITLE
ID not generated for TQ if not there are not many TQs

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#563]

**Comment by birchamp** [comment]
@kintsoogi a while back we had this problem in tCC. @mandolyte wrote code to prevent TSVs with duplicate IDs from being opened. But the users then have to go back and replace the ids with made up numbers. In that case should we just fix the bad Ids dynamicaly?

**Comment by PhotoNomad0** [comment]
@birchamp @kintsoogi - at one point we only required there to be unique ids for each verse reference.  But then we later started tightening those requirements.  I think @mandolyte worked on that effort.

**Comment by PhotoNomad0** [comment]
@birchamp Probably should warn users before id's are update dynamically and give them the option to cancel that.
