### ISSUE TITLE
Get 500 error on saving changes

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#564]
Users sometimes get 500 error on saving changes.  See screenshot below:

~~Seems this problem appears when there is just a small whitespace change - the library that generates the patch creates an empty patch that DCS does not like.~~

<img width="1680" alt="C4AEF809-F3B9-4C2D-B212-13DB581531C6" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/fb0f3caa-87ec-4d0a-91db-89becaa59a9e">

**Comment by abelpz** [comment]
I can confirm this is happening to us too @PhotoNomad0, it has happened with three different verses, and with bigger changes too.

**Comment by elsylambert** [comment]
To be tested on Develop link.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This should be fixed in latest develop.

**Comment by danielklapp** [comment]
@PhotoNomad0 Not getting the 500 error but getting Network Error with code 401 on saving. Here's attached console log
[develop--gateway-edit.netlify.app-1699592392751.log](https://github.com/unfoldingWord/gateway-edit/files/13315845/develop--gateway-edit.netlify.app-1699592392751.log). Tested with v2.1.0 build e2d994b QA

**Comment by elsylambert** [comment]
Tried to save ULT on develop link.
First save looked good, but then saved a whitespace and this error showed up as Manifest failed to load
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--958a242f706529eee87174c5dd3520f59305c192/Screenshot%202023-11-10%20at%209.36.49%E2%80%AFAM.png)

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This is likely happening when there is a problem reloading the verse.  The app gets stuck thinking the changes are not saved.  Unfortunately not having a reliable way to reproduce this is hindering progress on a solution.

**Comment by PhotoNomad0** [comment]
**Notes** - the 500 error can happen if
- patch is empty
- patch does not match the repo due to:
  - wrong file sha
  - patch not compatible with original file

**Options:**
- on error refetch repo and check file sha
- if changed then check to see if change was already applied
- otherwise generate new patch and try again.

**Comment by elsylambert** [comment]
While testing #565, I found saving error in ULT while saving the alignment.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89bb93681d0909f06c1d33a6821b7d68c7fa5039/Screenshot%202023-11-16%20at%209.04.10%E2%80%AFAM.png)

**Comment by PhotoNomad0** [comment]
> While testing #565, I found saving error in ULT while saving the alignment. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89bb93681d0909f06c1d33a6821b7d68c7fa5039/Screenshot%202023-11-16%20at%209.04.10%E2%80%AFAM.png)

I think there is another issue for that one that error.  401 errors are typically when you are no longer logged in.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This is fixed in GWE v2.1.0 build 19c7052

**Comment by elsylambert** [comment]
Not seeing 500 error in v2.1.0 build 19c7052 QA while saving ULT/UST.
