### ISSUE TITLE
Add Alignment validation and migration to each verse

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#565]
This is split out of issue https://github.com/unfoldingWord/gateway-edit/issues/562 - will leave the other issue open until we can determine how to reproduce the corruption seen.

Tasks to do:
- [ ] on first navigation to a verse, the alignment indicator will show broken if target words are aligned to an original word not found in the original language bible
- [ ] on click to open alignments, existing alignments will be migrated to match latest original language and falling back to normalized matching if exact word match not found.  Any alignments to original language words not found in the original language bible will be removed.
- [ ] after verse edit, existing alignments will be migrated to match latest original language and falling back to normalized matching if exact word match not found.  Any alignments to original language words not found in the original language bible will be removed.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp - This is now in GWE v2.1.0 build f845565.  Still working on a way to test...

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp OK have a way to test on qa server using test_org/en.  I made some changes in the master branch on qa (so testing should work for this week)

- in Gal 1:1  I modified the alignment word for Peter which makes the original alignment invalid.  So when you go there you should see an invalid alignment icon:

<img width="993" alt="Screenshot 2023-11-14 at 1 31 42 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/3f26435d-08bf-4603-9794-ead661c13977">

- then click the alignment icon and should see Peter not aligned:

<img width="1007" alt="Screenshot 2023-11-14 at 1 32 32 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/e2206206-96e0-43db-87d2-dd81d6b6fecd">

- in Gal 1:2 I modified the alignment word for borthers (and the lemma) which makes the original alignment invalid.  So when you go there you should see an invalid alignment icon:

<img width="503" alt="Screenshot 2023-11-14 at 1 40 11 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/1a178fb6-7dde-4021-9c7a-33aee5a5a4c9">

- then click the alignment icon and should see brothers not aligned:

<img width="912" alt="Screenshot 2023-11-14 at 1 40 43 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/8afbe0c0-f9e6-45ef-8be7-1cdb1310a783">

**Comment by danielklapp** [comment]
@PhotoNomad0 is there a DOD for this issue?

**Comment by elsylambert** [comment]
Verified in v2.1.0 build f845565 QA with the test steps  provided, alignment validation works as expected.
However, I found the saving error when I tried to save the alignment for "Brothers" in the second step, will update it in #564 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUxmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24169dc3a7f37e140f8cd235126eb2a1a615ca4c/Screenshot%202023-11-16%20at%209.04.10%E2%80%AFAM.png)

**Comment by danielklapp** [comment]
@PhotoNomad0 in testing the steps yesterday I was thinking I was missing something. I've retested alignment validation and it's working properly. Tested with v2.1.0 build f845565 QA.
