### ISSUE TITLE
gE features: Remember the size of the editing box.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#566]
**Problem Statement**

**Proposed Solution **

**Details**

**Additional context**

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp there is overlap here with issue https://github.com/unfoldingWord/gateway-edit/issues/523

**Comment by elsylambert** [comment]
Thanks Bruce, you found the issue we were looking for, yesterday. Will
close the duplicate issue.
