### ISSUE TITLE
Clear/reset the alignments 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#569]
**Problem Statement**
If the user wants to clear all the previous alignments or half aligned words, they have to manually move every aligned word which is cumbersome.

**Proposed Solution**
Provide a button to clear the alignments that should  send all the words to sent back to the word bank allowing the user to start over fresh.

**Details**
On clicking the  Clear alignment button, there should be a prompt for the user to confirm if they want to claer the alignments. This is necessary to avoid accidental clicks. If user selects Yes> this should  send all the words to sent back to the word bank; If No then the words/alignment should stay as is.

**Additional context**

**Comment by elsylambert** [comment]
Looks good in v2.1.0 build f845565 QA. Clear/Reset button is available in Alignment screen and it works as expected. When clicked, a prompt is shown which confirms if the user wants to clear alignments. On selecting Yes, all words are sent bank to word bank and when Cancel is selected after that, no alignment is lost.

**Comment by danielklapp** [comment]
Agree that Alignment has a Reset button and it works as stated above. Looks good to me. Tested with v2.1.0 build f845565 QA.
<img width="882" alt="Screenshot 2023-11-14 at 3 38 54 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/8b2abf46-5ef9-4d76-981f-ec9a00cb50c1">
