### ISSUE TITLE
See crash sometimes on first run in Account Settings

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#57]
Need steps to reproduce. 

DoD:  

See this error screen:

![Screen Shot 2021-02-11 at 8.34.57 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/60a9a9b7-3be1-4df5-9a00-5917e83ff31d)

Seems to be two problems here:

- [ ] login credentials are being lost even though saved (seems the only way to recover is to log out and back in again)
- [ ] need better error handling when fetch of organizations fails (such as when user does not yet belong to any orgs)

**Comment by mandolyte** [comment]
@PhotoNomad0 I attempt to use create-app today (so a first time login). I got an "unexpected error message" error.

Here is the console:
![image](https://user-images.githubusercontent.com/1289437/109150858-6b2dc380-7737-11eb-94c4-459324c40f7c.png)


The 404 was on this link: https://git.door43.org/unfoldingWord/en_tq/raw/branch/master/mat

And of course, that is not a valid filename in en_tq; it is a folder. Since the switch to TSV is coming near... not sure I'd try to fix this at this point?

will try your work around above... just wanted to add this

**Comment by mandolyte** [comment]
The work around didn't work either. I tried logging in several times. Here is snippet:
![image](https://user-images.githubusercontent.com/1289437/109151690-7c2b0480-7738-11eb-8140-4208cfbe2678.png)

**Comment by birchamp** [comment]
@mannycolon @ancientTexts-net check out how 1.0 is handling the token. Per @klappy this could be how the SHA is being stored.

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @elsylambert  The app no longer crashes when token does not work.  So the error handling is now working:

<img width="669" alt="Screen Shot 2021-03-29 at 7 49 07 AM" src="https://user-images.githubusercontent.com/14238574/112832474-5f4d5e00-9063-11eb-8618-01fb961fc6ec.png">

In the console log I see that we are now logging the specific error code. 

<img width="632" alt="Screen Shot 2021-03-29 at 7 53 37 AM" src="https://user-images.githubusercontent.com/14238574/112832874-ef8ba300-9063-11eb-9cc4-00bbd3528197.png">

We could change the error message here to tell the user that they need to log in again.  Something like **"Your login is no longer valid.  You need to login again."**

Do we want to present the option to go to login screen?  We could put a login button here if they are no longer authenticated.

I don't think there is a way automatically refresh the token since we don't save the password.

**Comment by PhotoNomad0** [comment]
@birchamp On second thought, since this is the gatewayEdit app, I think we should revalidate the token on app startup and take the user to the login screen if the token is invalid. That would handle use cases such as when token has been deleted on DCS. @cckozie

**Comment by PhotoNomad0** [comment]
Notes:
token issues:
- when logged in on a different computer or browser, DCS creates a new token and older token becomes invalid.
- in create 1.0 app, it will delete old tokens from DCS on login

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert Fix is in v0.9.0 build a6e30e1

**Comment by cckozie** [comment]
v0.9.0 build 3e62f25
Have not seen a crash on first run.
Verified that logging in to a different browser will force re-login on original browser.

**Comment by elsylambert** [comment]
v0.9.0 build 3e62f25
Not seeing the app crash but I am able to use the app in two different browsers at the same time. Not seeing a force login in either of the browser.
Also I have the app opened in two tabs in the same browser and it does not do a force login.

**Comment by PhotoNomad0** [comment]
> v0.9.0 build [3e62f25](https://github.com/unfoldingWord/gateway-edit/commit/3e62f25ebc699a7ba506ff8d8d03afb9a2a50782)
> Also I have the app opened in two tabs in the same browser and it does not ask for a force login.

This is expected behavior since localStorage is saved based on the url.

**Comment by PhotoNomad0** [comment]
> v0.9.0 build [3e62f25](https://github.com/unfoldingWord/gateway-edit/commit/3e62f25ebc699a7ba506ff8d8d03afb9a2a50782)
> Not seeing the app crash but I am able to use the app in two different browsers at the same time. Not seeing a force login in either of the browser.

@elsylambert  Can you share the steps to reproduce this?  I am not seeing this.

**Comment by elsylambert** [comment]
Steps:
1. open the gateway edit app in chrome and login, select a book and navigate through the notes.
2. Open another browser, (I opened Safari) login using the same ID, select same organization and language, select a book and navigate through it.
3. Go back to the Browser opened in step 1. Note that you are able to navigate through the selected book and notes.

**Comment by PhotoNomad0** [comment]
That is expected behavior.  We currently only recheck tokens when app is opened (or refreshed).

**Comment by elsylambert** [comment]
Passing this issue, Mutli-session user logins/token validation would be handled by Editing part of the app.
Currently it works as expected.
