### ISSUE TITLE
Line spacing in Hebrew text to be increased to avoid overlapping 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#575]
**Problem Statement**
The Hebrew currently displays in such a way that the lines overlap:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMS9FQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5798003bc8356167f42f5188ec80f677e850a340/image.png)

**Proposed Solution **
the Line spacing between Hebrew text to be at 2.0em

**Details**
Current line spacing is 0.5em
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkhFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--007f90f060a2c345726440f35da864c4d270605c/image.png)
If the line spacing is set to 2.0 em it should look like this:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlRFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1ddaccdf993cd0915d17a61154f479a9c59074e/image.png)

DoD: Hebrew text should not overlap and have good line spacing(2.0em)

**Comment by elsylambert** [comment]
Looks good in v2.3.0 build 06539c8 QA. Line spacing for Hebrew text is 2.0.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGVoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a885ad27a355359e12b7de6bf7b32f694a814b67/Screenshot%202024-01-04%20at%2011.27.42%E2%80%AFAM.png" alt="Screenshot 2024-01-04 at 11.27.42 AM.png" />

**Comment by danielklapp** [comment]
Agree that the line-height is set to 2.0em for Hebrew text. Tested with v2.3.0 build 06539c8 QA.
