### ISSUE TITLE
Crash Navigating to tit on test_org/en

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#577]
using GWE v2.1.0 build f845565 QA - When I set organization to test_org and language to en, it opens to Matthew.  But when I change the book to tit, I see this crash:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVRSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9332ed473d562e9bff99ba01e46a30c1afdb7359/Screenshot%202023-11-14%20at%208.39.36%E2%80%AFAM%20%282%29.png)

**Comment by PhotoNomad0** [comment]
It seems quite reproducible.

**Comment by PhotoNomad0** [comment]
@kintsoogi This is the problem we saw before:

<img width="1442" alt="Screenshot 2023-11-14 at 1 51 50 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/8d0c2c68-00d3-4256-8c64-ba79db4f49d7">

It looks like there is a problem that someone did a hand edit on one of the lines:

<img width="801" alt="Screenshot 2023-11-14 at 1 59 37 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/14238574/1e2fcb5b-f1e3-4c8f-b8d1-ded133d82852">

Should probably make the code more rugged so we don't crash on invalid tsv lines.

Another issue seems to be that this function is being called repeatedly even when we are not adding a row.  In this case, if we do a refresh we hit this error before rendering even begins.

**Comment by danielklapp** [comment]
Not seeing this issue of crashing. Looks good with v2.1.0 build 65fd995 QA.
