### ISSUE TITLE
New row is added in tQ without an ID

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#578]
As reported in #563, IDs are not generated in TQs for new rows and if user leaves the  ID empty, the new row is added with the ID.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejNaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c7db2e248615aa473795053b92f070434f4dc7b/Screenshot%202023-11-15%20at%209.53.51%E2%80%AFAM.png)

**Comment by danielklapp** [comment]
Seeing IDs being generated in TQs for newly added rows. Tested  with v2.1.0 build 65fd995 QA.
<img width="1153" alt="Screenshot 2023-11-17 at 4 33 01 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/c4ff4826-864b-4fcd-a56b-a096f92df3df">

**Comment by elsylambert** [comment]
v2.1.0 build 19c7052 QA, Add row in tQ looks good. 

I have reported Add New Row Bug in TN in #588 @kintsoogi
