### ISSUE TITLE
For TWL, no add button exists when there are no TSV items since the add buttons are in the individual rows

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#585]

**Comment by elsylambert** [comment]
Looks good in v2.1.0 build 868a6c3 QA. Add button is available for TWL when no content is available at first. Delete button is not available unless a row is added.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3acee8c1d6c8e9a885f4c9a7011828e37bbf70fb/Screenshot%202023-11-28%20at%2010.30.00%E2%80%AFAM.png)

**Comment by danielklapp** [comment]
When navigating to a reference where there’s no content or has been deleted in TWL, user can see the add button in header. Delete button shows up when user adds a row. Tested with v2.1.0 build 868a6c3 QA.

<img width="1068" alt="Screenshot 2023-11-28 at 11 12 57 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/f34f6ebe-a6d4-4542-954c-8431d0387080">

<img width="1072" alt="Screenshot 2023-11-28 at 11 08 36 AM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/fab221e1-5f70-45fa-b3bb-91d0cd14d427">
