### ISSUE TITLE
Delete TWL that includes a Reference Range

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#593]
When deleting a row with a reference range the user should be able delete that row the same as a single verse row.

DoD
---
Deleting any TWL should remove the row from the TSV.

**Comment by elsylambert** [comment]
v2.3.0 build bd4a646 QA. Delete row that has a refernce range works fine, but I found that the Delete row dialog has this text:
<img width="1191" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM055QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--731663817d6ef9ccdbcddbbe1d5f32a48329f695/Screenshot%202023-12-19%20at%209.48.13%E2%80%AFAM.png" alt="Screenshot 2023-12-19 at 9.48.13 AM.png" />

**Comment by elsylambert** [comment]
Moving this issue to QA fail for your attention @kintsoogi 
The feature looks good but only needs fix for the text shown in the modal ^^.

**Comment by elsylambert** [comment]
Looks good in v2.3.0 build 06539c8 QA. Not seeing _refernceRange in delete dialog box.

**Comment by danielklapp** [comment]
Not seeing _referenceRange under the Note in Delete This TSV Item? window. Tested with v2.3.0 build 06539c8 QA.
