### ISSUE TITLE
Scripture is not showing reference ranges

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#601]
Scripture reference ranges are shown when translation note with range is the first element on the list when the page is loaded.
However, when a range is added or navigated to by clicking the arrows, the reference range is shown for a quick second and then scripture just shows a single verse.

DoD
---
Scripture shows reference range when new note is added and when reference range is navigated to when not first translation note.

**Comment by elsylambert** [comment]
Verified in v2.3.0 build bd4a646 QA. Scripture pane shows the reference ranges when a tN has a reference range in it.
<img width="1191" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlp5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--890d7f9e007a257756db5e9703a426b8ef7051c0/Screenshot%202023-12-19%20at%209.47.20%E2%80%AFAM.png" alt="Screenshot 2023-12-19 at 9.47.20 AM.png" />

**Comment by danielklapp** [comment]
Looks good to me. Tested with v2.3.0 build bd4a646 QA.
