### ISSUE TITLE
Save button is enabled when edit box is clicked 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#602]
v2.2.0 build 7018555 QA
On UST/ULT or other resource cards, when user clicks in the edit box to edit save button is enabled before any edits are made.
- Click on the ULT resource card edit box.
- Note that save button is enabled.
- Click out of the box without making any edit and note that the Save button is still enabled.
- Navigate to next verse from the top navigation bar and browser throws warning that changes are not saved.
- Click on Save button and it does not Save. Note that the console shows Nothing to save.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aad7dcf1db52b17d57d72d3ffa83fbe690f5ebf1/Screenshot%202023-11-29%20at%205.19.12%E2%80%AFPM.png)

DOD: If the user has not made any edits, Save button should not get enabled.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp The fix is in release branch v2.2.0 build 6765008 QA

**Comment by elsylambert** [comment]
Looks good in v2.2.0 build 3179311 QA. Not seeing save button enabled when text box is clicked.

**Comment by danielklapp** [comment]
Looks good to me. Tested with v2.2.0 build 6765008 QA.
