### ISSUE TITLE
Add row dialog for TN in Psalms shows empty fields 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#636]
Add row dialog for TN in Psalms shows empty fields and does not show all of the columns fields as shown in the snapshot:

<img width="1524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca11eed267770cc850eac3005dbb3da501d4ece1/Screenshot%202024-01-05%20at%2010.41.57%E2%80%AFAM.png" alt="Screenshot 2024-01-05 at 10.41.57 AM.png" />

v2.3.0 build 06539c8 QA. https://develop--gateway-edit.netlify.app/ org- unfoldingWord, en, Book- PSA.

**Comment by elsylambert** [comment]
Delete shows as below:
<img width="1524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXloQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--760aa64eed19d0b694a22a6f69b82fe8d62be85e/Screenshot%202024-01-05%20at%2010.59.01%E2%80%AFAM.png" alt="Screenshot 2024-01-05 at 10.59.01 AM.png" />

**Comment by danielklapp** [comment]
Agree that all input fields are shown in tN card when adding a row for the book of Psalms. Tested with v2.3.0 build 8f589a0 QA.
