### ISSUE TITLE
Site crashes after adding new translation note row with a reference range 

### ISSUE THREAD

**Issue by danielklapp** [unfoldingWord/gateway-edit#637]
When user creates a new translation note row that has reference range with an existing chapter&verse that’s in a book, and chapter&verse that doesn’t exist in that book. The row shows up in translationNotes, but when clicking on previous or next button the site crashes.

Example :

- Open to the book of Hag and add new TSV row with reference range (2:3; 3:4). 
  (There is only two chapters in this book. So chapter three doesn’t exist) 

- Navigate to Hag 2:3 and in tN card click next button to get to newly added row with Reference (2:3; 3:4).

- After reference shows in new TSV row click either previous or next button the site crashes. 

<img width="1978" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0doQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2b0f19ba31d7ffc8db922e64ab6a3c3b7357f4e/Screenshot%202024-01-05%20at%2010.49.51%E2%80%AFAM.png" alt="Screenshot 2024-01-05 at 10.49.51 AM.png" />

v2.3.0 build 06539c8 QA

**Comment by danielklapp** [comment]
@kintsoogi I updated the steps to replicate this issue.

**Comment by elsylambert** [comment]
v2.3.0 build 8f589a0 QA. Not seeing a crash when an invalid Reference is entered in the reference field. It does not  create a row in such case. We can see error in the console for invalid row input.

**Comment by danielklapp** [comment]
Invalid new row input error is shown in console when user types an invalid reference. Invalid row isn't created and site not crashing when navigating the next and previous buttons. Looks good and tested with v2.3.0 build 8f589a0 QA.
