### ISSUE TITLE
Remove "Remove Resource Card" link from the settings card.

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#67]
The option to "Remove Resource Card" needs to be removed from the settings card.

**Comment by cckozie** [comment]
Not seeing the Remove Resource Card link from the setting card related to any type of resource card in v0.2.0 build cbad9c9

**Comment by elsylambert** [comment]
v0.9.0 build ab13659
Not seeing "Remove Resource card" link in the settings card.
