### ISSUE TITLE
Add button to reset the workspace layout (resourceLayout)

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gateway-edit#78]
Add a reset layout button so that when the default layout is changed the user has a way to avoid quirky layouts as shown below

![Screen Shot 2021-03-02 at 11 02 07 AM](https://user-images.githubusercontent.com/17072300/109676609-de27a780-7b46-11eb-9082-b2d2c572e969.png)

**Comment by mannycolon** [comment]
After manually resetting the `resourceLayout` value in local storage 

![Screen Shot 2021-03-02 at 11 02 07 AM](https://user-images.githubusercontent.com/17072300/109677069-4aa2a680-7b47-11eb-8139-88c89471deef.png)

**Comment by elsylambert** [comment]
Works as expected in v0.9.0 build 4ec92f2.
