### ISSUE TITLE
Add "how to" text to version dropdown

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-edit#89]
The user needs to know what to do to add a new version to the scripture card. 
* Can this be done within the dropdown itself as an item in the list "add new version"?
* Do dropdowns have an option for default text that's overwritten when the user begins typing? 

Review the video: https://images.zenhubusercontent.com/310359593/e69124ce-501e-4b30-a1f3-2076233e0922/screencast_2021_03_11_14_48_25.mp4

**Comment by birchamp** [comment]
@PhotoNomad0 check out the video above. What do you think?

**Comment by birchamp** [comment]
Here's an example of what I was talking about @PhotoNomad0 
https://codesandbox.io/s/material-demo-forked-82z91?file=/demo.js

**Comment by cckozie** [comment]
Looks good in v0.9.0 build 87451c8

**Comment by elsylambert** [comment]
Looks good in v0.9.0 build 4ec92f2. Seeing the text change in the scriptures settings card. On adding a bad URL, user is alerted that the uRL is invalid.
