### ISSUE TITLE
Users should not be able to shrink the width or height of cards to the point where elements are moved off of the card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#92]
Issue:
---
When the user attempts to reduce the size of the card to the extent that the text is outside of the card the UI should not permit the card to shrink further. 

DoD:
---
A card should contain all of its text when shrunk to its minimum state through the use of scrollbars and limiting the minimum size. 

Details:
---
Here are some examples of the current problem

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/0a49c308-151c-4893-a295-23cc5c15ac0d)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/ae6580b8-c6e1-46cb-bf5b-bddfa49fb9b7)

**Comment by PhotoNomad0** [comment]
Klappy discovered that this can be fixed by adding overflow hidden to title

**Comment by cckozie** [comment]
It is looking good in v0.9.0 build f601ed4

**Comment by elsylambert** [comment]
Looks good in v0.9.0 build f601ed4. The cards cannot be shrunk to the point where the contents hang out of the card.
