### ISSUE TITLE
Font sizing does not work on tA, tW, and tQ resources

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#94]
Issue:
---
The dialog for resizing appears, but the font size does not actually change regardless of the setting. Changing the font size setting should change the size of the font on the associated card.

DoD:
---
Changing the font size setting changes the font size of the associated card.

**Comment by cckozie** [comment]
v0.9.0 build 008141c
On the tA card the headings do not change size.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/b89ad773-1a20-4793-8e53-650bdd25e14e)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/48861d68-cd66-44d2-bbf5-95b9a0f5ef44)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/70d1413e-65b4-4475-a753-e5e3855d8cc9)

**Comment by cckozie** [comment]
Works as expected in v0.9.0 build 2f4b7ee

**Comment by elsylambert** [comment]
Font sizing on resource cards works fine in v0.9.0 build 2f4b7ee.

**Comment by cckozie** [comment]
Tested in Test Persistence by User
