### ISSUE TITLE
Font size settings are only persisted for scripture resources

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#95]
Issue:
---
The font size setting for all other resources is not persisted when the user logs out or when he opens a new session.

DoD:
---
Font sizes for all of the cards should be maintained across a user logout/login or new session.

**Comment by cckozie** [comment]
Works correctly in v0.9.0 build 008141c

**Comment by elsylambert** [comment]
Font sizes are persisted on resources and scripture cards in v0.9.0 build 008141c.c

**Comment by cckozie** [comment]
Tested in Test Persistence by User
